import fs from 'fs';
import path from 'path';

const postcastRoot = 'E:\\VIDEO AND SOUND\\POSTCAST';

// 1. TẠO FILE HƯỚNG DẪN & QUY HOẠCH TOÀN BỘ POSTCAST (.txt)
const overviewLines = [
  "================================================================================",
  "🛕 TÙNG LÂM HÒA PHÚC — QUY HOẠCH DỮ LIỆU & BỔ SUNG PHÁP THOẠI POSTCAST 🛕",
  "================================================================================",
  "Thư mục: E:\\VIDEO AND SOUND\\POSTCAST\\",
  "",
  "Kính thưa Ban Văn Thư & Ban Hoằng Pháp,",
  "",
  "Thư mục POSTCAST đã được rà soát, quy hoạch và bổ sung đầy đủ các bài pháp thoại",
  "quan trọng từ các thư mục khác (PHÁP THOẠI, SU_PHU, LÁ THƯ, CẢNH SÁCH, TỤNG KINH...).",
  "",
  "🌟 TRUNG TÂM PHÁP THOẠI HOÀN CHỈNH:",
  "👉 E:\\VIDEO AND SOUND\\POSTCAST\\00_TONG_HOP_SERIES_PHAP_THOAI_HOAN_CHINH\\",
  "",
  "Nơi đây lưu giữ toàn bộ 10 Series Pháp thoại tinh hoa đã được biên tập sạch,",
  "đổi tên tiếng Việt chuẩn mực, có đánh số thứ tự khoa học để phục vụ 3 mục đích:",
  "  1. Copy trực tiếp cho Quý Phật tử nghe pháp (USB / Thẻ nhớ / Zalo / Drive).",
  "  2. Đăng tải lên YouTube / Spotify Podcast theo từng Series chuẩn SEO.",
  "  3. Đồng bộ vào Cơ Sở Dữ Liệu Website Tùng Lâm Hòa Phúc (tunglamhoaphuc.com).",
  "",
  "--------------------------------------------------------------------------------",
  "CHI TIẾT 10 SERIES PHÁP THOẠI ĐÃ ĐƯỢC TỔNG HỢP VÀ BỔ SUNG:",
  "--------------------------------------------------------------------------------",
  "",
  "📂 01_SERIES_DAI_MUC_KIEN_LIEN (09 TẬP)",
  "   • Giảng sư: Đại đức Thích Tâm Hòa",
  "   • Tập 01: Hạnh Nguyện Ban Sơ",
  "   • Tập 02: Ưu Tư Thời Niên Thiếu",
  "   • Tập 03: Khơi Nguồn Hạnh Nguyện",
  "   • Tập 04: Giữ Vững Chí Nguyện",
  "   • Tập 05: Tự Do Đích Thực",
  "   • Tập 06: Mục Đích Tối Hậu",
  "   • Tập 07: Giữ Chất Người Tu",
  "   • Tập 08: Cánh Cửa Bất Tử",
  "   • Tập 09: Đạo Lộ Giải Thoát",
  "   • Kèm tài liệu Marker & Timestamps 9 buổi phục vụ làm video và đăng bài.",
  "",
  "📂 02_SERIES_HIEU_DUONG_CHA_ME_KINH_A_HAM (03 TẬP)",
  "   • Giảng sư: Đại đức Thích Tâm Hòa",
  "   • Phần 01: Lời Phật Dạy Về Hiếu Dưỡng Cha Mẹ",
  "   • Phần 02: Hạnh Phúc Gia Đình",
  "   • Phần 03: Báo Đáp Thâm Ân",
  "",
  "📂 03_SERIES_PHAP_AM_CHUYEN_HOA_TAM_LY (SA-MÔN VÔ TRÍ)",
  "   • Giảng sư: Sa-môn Vô Trí",
  "   • Bài 01: Làm Thế Nào Để Gia Đình Hạnh Phúc",
  "   • Bài 02: Làm Cách Nào Để Duy Trì Sự Bình An",
  "   • Bài 03: Đâu Là Con Đường Đi Đến Hạnh Phúc",
  "   • Bài 04: Làm Việc Hiệu Quả Trong Chánh Niệm",
  "",
  "📂 04_SERIES_BO_DE_TAM_HANH_TRI_NGHI_QUY",
  "   • Giảng sư: Đại đức Thích Tâm Hòa",
  "   • Bài 01: Điều Gì Giúp Người Con Phật Luôn Vững Vàng",
  "   • Kèm file tài liệu Word bài giảng chi tiết Buổi 1, Buổi 2, Buổi 3.",
  "",
  "📂 05_SERIES_CONG_TU_MOT_NGAY_AN_LAC (ĐÃ BỔ SUNG)",
  "   • Bài 01: Một Góc Nhìn Về Thực Dưỡng Oshawa Dưới Ánh Sáng Phật Pháp (Bổ sung mới)",
  "   • Bài 02: Tóm Tắt Chương Trước - Một Ngày An Lạc",
  "   • Bài 03: Cộng Tu Một Ngày An Lạc Tháng 07",
  "   • Bài 04: Giới Luật - Nền Tảng Của Người Tu",
  "",
  "📂 06_SERIES_PHAP_HOI_NIEM_PHAT_CTNP",
  "   • Bài 01: Thấy Nghiệp Để Chuyển Hóa, Giữ Giới Để Tiến Tu - ĐĐ. Thích Tâm Hòa",
  "   • Bài 02: Pháp Hội Niệm Phật 03 - Hương Vị Giải Thoát",
  "",
  "📂 07_SERIES_KINH_DI_GIAO_PPUD",
  "   • Kế hoạch & Trích đoạn Timeline Kinh Di Giáo - ĐĐ. Thích Tâm Hòa",
  "",
  "📂 08_SERIES_LA_THU_KHAI_THI_VA_CANH_SACH (ĐÃ BỔ SUNG ĐẦY ĐỦ)",
  "   • Bài 01: Lá Thư Khai Thị Trước Thềm Năm Bính Ngọ - Thầy Viện Chủ Thích Tâm Hòa (Bổ sung)",
  "   • Bài 02: Lá Thư Mùa Trung Thu - Thầy Viện Chủ Thích Tâm Hòa (Bổ sung)",
  "   • Bài 03: Khai Tràng Thảm Lễ Nghi Thức Cúng Đàn (20 Phút) (Bổ sung)",
  "   • Bài 04: Cảnh Sách Diễn Nôm Sáng Chiều - ĐĐ. Minh Hạnh (Bổ sung)",
  "   • Bài 05: Cảnh Sách Ngày Trai Buổi Chiều - ĐĐ. Minh Hạnh (Bổ sung)",
  "   • Bài 06: Cảnh Sách Ngày Trai Buổi Sáng - ĐĐ. Minh Hạnh (Bổ sung)",
  "",
  "📂 09_SERIES_KHOA_TU_TUOI_TRE_VA_PHUNG_SU (ĐÃ BỔ SUNG)",
  "   • Bài 01: Trái Tim Người Phụng Sự - ĐĐ. Thích Tâm Hòa",
  "   • Bài 02: Pháp Đàm Khóa Tu Tuổi Trẻ Buổi 1 (Bổ sung)",
  "",
  "📂 10_SERIES_KHOA_LE_TRUYEN_THONG_VA_TUNG_KINH (ĐÃ BỔ SUNG)",
  "   • Bài 01: Pháp Thoại Huyết Bồn Trai Ngày 1",
  "   • Bài 02: Pháp Thoại Huyết Bồn Trai Ngày Khai Đàn",
  "   • Bài 03: Tụng Tỳ Ni Nhật Dụng Thiết Yếu - Bản Gốc (Bổ sung)",
  "   • Bài 04: Sám Nguyện - ĐĐ. Thích Thiện Mỹ (Bổ sung)",
  "",
  "--------------------------------------------------------------------------------",
  "LƯU Ý QUAN TRỌNG:",
  "Toàn bộ các thư mục dự án gốc (WAV, sesx, prproj) trong POSTCAST vẫn được giữ",
  "nguyên vẹn 100% để bảo đảm an toàn dữ liệu cho các editor kỹ thuật.",
  "================================================================================"
];

fs.writeFileSync(path.join(postcastRoot, '00_DANH_MUC_VA_QUY_HOACH_POSTCAST.txt'), overviewLines.join('\r\n'), 'utf8');

// 2. TẠO FILE BẢNG TRA CỨU EXCEL CSV (CÓ UTF-8 BOM)
const csvRows = [
  ["STT", "MÃ BÀI", "SERIES", "TÊN BÀI PHÁP THOẠI", "GIẢNG SƯ", "THỜI LƯỢNG", "ĐỊNH DẠNG", "TRẠNG THÁI", "ĐÃ LÊN WEB"],
  ["1", "#phapthoai 001", "Tôn Giả Mục Kiền Liên", "Hạnh Nguyện Ban Sơ", "ĐĐ. Thích Tâm Hòa", "75 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["2", "#phapthoai 002", "Tôn Giả Mục Kiền Liên", "Ưu Tư Thời Niên Thiếu", "ĐĐ. Thích Tâm Hòa", "82 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["3", "#phapthoai 003", "Tôn Giả Mục Kiền Liên", "Khơi Nguồn Hạnh Nguyện", "ĐĐ. Thích Tâm Hòa", "56 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["4", "#phapthoai 004", "Tôn Giả Mục Kiền Liên", "Giữ Vững Chí Nguyện", "ĐĐ. Thích Tâm Hòa", "65 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["5", "#phapthoai 005", "Tôn Giả Mục Kiền Liên", "Tự Do Đích Thực", "ĐĐ. Thích Tâm Hòa", "70 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["6", "#phapthoai 006", "Tôn Giả Mục Kiền Liên", "Mục Đích Tối Hậu", "ĐĐ. Thích Tâm Hòa", "85 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["7", "#phapthoai 007", "Tôn Giả Mục Kiền Liên", "Giữ Chất Người Tu", "ĐĐ. Thích Tâm Hòa", "62 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["8", "#phapthoai 008", "Tôn Giả Mục Kiền Liên", "Cánh Cửa Bất Tử", "ĐĐ. Thích Tâm Hòa", "78 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["9", "#phapthoai 009", "Tôn Giả Mục Kiền Liên", "Đạo Lộ Giải Thoát", "ĐĐ. Thích Tâm Hòa", "66 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["10", "#phapthoai 010", "Kinh Tạp A Hàm", "Lời Phật Dạy Về Hiếu Dưỡng Cha Mẹ - Phần 1", "ĐĐ. Thích Tâm Hòa", "68 phút", "MP3 / MP4", "Hoàn tất podcast", "Có"],
  ["11", "#phapthoai 011", "Kinh Tạp A Hàm", "Hiếu Dưỡng Cha Mẹ - Phần 2 - Hạnh Phúc Gia Đình", "ĐĐ. Thích Tâm Hòa", "62 phút", "MP3 / MP4", "Hoàn tất podcast", "Có"],
  ["12", "#phapthoai 012", "Kinh Tạp A Hàm", "Hiếu Dưỡng Cha Mẹ - Phần 3 - Báo Đáp Thâm Ân", "ĐĐ. Thích Tâm Hòa", "70 phút", "MP3 / MP4", "Hoàn tất podcast", "Có"],
  ["13", "#phapthoai 013", "Pháp Âm Chuyển Hóa", "Làm Thế Nào Để Gia Đình Hạnh Phúc", "Sa-môn Vô Trí", "58 phút", "MP3", "Hoàn tất master", "Có"],
  ["14", "#phapthoai 014", "Pháp Âm Chuyển Hóa", "Làm Cách Nào Để Duy Trì Sự Bình An", "Sa-môn Vô Trí", "54 phút", "MP3", "Hoàn tất master", "Có"],
  ["15", "#phapthoai 015", "Pháp Âm Chuyển Hóa", "Đâu Là Con Đường Đi Đến Hạnh Phúc", "Sa-môn Vô Trí", "60 phút", "MP3", "Hoàn tất master", "Có"],
  ["16", "#phapthoai 016", "Pháp Âm Chuyển Hóa", "Làm Việc Hiệu Quả Trong Chánh Niệm", "Sa-môn Vô Trí", "52 phút", "MP3", "Hoàn tất master", "Có"],
  ["17", "#phapthoai 017", "Bồ Đề Tâm Nghi Quỹ", "Điều Gì Giúp Người Con Phật Luôn Vững Vàng", "ĐĐ. Thích Tâm Hòa", "45 phút", "MP3 / DOCX", "Hoàn tất master", "Có"],
  ["18", "#phapthoai 018", "Lá Thư Sư Phụ", "Lá Thư Trước Thềm Năm Bính Ngọ", "ĐĐ. Thích Tâm Hòa", "25 phút", "MP3 / MP4", "Hoàn tất master", "Có"],
  ["19", "#phapthoai 019", "Cảnh Sách Ngày Trai", "Cảnh Sách Diễn Nôm Sáng Chiều", "ĐĐ. Minh Hạnh", "18 phút", "MP3", "Hoàn tất master", "Có"],
  ["20", "#phapthoai 020", "Một Ngày An Lạc", "Một Góc Nhìn Về Thực Dưỡng Oshawa", "ĐĐ. Thích Tâm Hòa", "60 phút", "MP3", "Đã bổ sung", "Sẵn sàng"],
  ["21", "#phapthoai 021", "Lá Thư Sư Phụ", "Lá Thư Mùa Trung Thu", "ĐĐ. Thích Tâm Hòa", "15 phút", "MP3", "Đã bổ sung", "Sẵn sàng"],
  ["22", "#phapthoai 022", "Pháp Hội Niệm Phật", "Thấy Nghiệp Để Chuyển Hóa, Giữ Giới Để Tiến Tu", "ĐĐ. Thích Tâm Hòa", "75 phút", "MP3 / DOCX", "Hoàn tất master", "Sẵn sàng"],
  ["23", "#phapthoai 023", "Khóa Tu Tuổi Trẻ", "Trái Tim Người Phụng Sự", "ĐĐ. Thích Tâm Hòa", "50 phút", "MP3 / DOCX", "Hoàn tất master", "Sẵn sàng"],
  ["24", "#phapthoai 024", "Khóa Lễ Truyền Thống", "Tụng Tỳ Ni Nhật Dụng Thiết Yếu - Bản Gốc", "Chư Tăng Tùng Lâm", "90 phút", "MP3", "Đã bổ sung", "Sẵn sàng"]
];

const csvContent = '\uFEFF' + csvRows.map(row => row.map(cell => `"${cell.replace(/"/g, '""')}"`).join(',')).join('\r\n');
fs.writeFileSync(path.join(postcastRoot, '00_BANG_TRA_CUU_PHAP_THOAI_POSTCAST.csv'), csvContent, 'utf8');

console.log('✅ Đã tạo thành công 00_DANH_MUC_VA_QUY_HOACH_POSTCAST.txt');
console.log('✅ Đã tạo thành công 00_BANG_TRA_CUU_PHAP_THOAI_POSTCAST.csv');
