import fs from 'fs';

const parsedDocs = JSON.parse(
  fs.readFileSync('C:\\Users\\MY PC\\Tung_Lam_Hoa_Phuc_Web\\drive_download\\all_parsed_docs.json', 'utf8')
);

// Load current data to preserve custom videoBlock and edits
const currentData = JSON.parse(
  fs.readFileSync('C:\\Users\\MY PC\\Tung_Lam_Hoa_Phuc_Web\\src\\data\\tong-chi-data.json', 'utf8')
);

const existingMap = {};
for (const item of currentData) {
  existingMap[item.id] = item;
}

const CATEGORIES_DEF = {
  'tong-phong-truyen-thua': 'TÔNG PHONG TRUYỀN THỪA',
  'nen-tang-tu-hoc': 'NỀN TẢNG TU HỌC',
  'phuong-phap-hanh-tri': 'PHƯƠNG PHÁP HÀNH TRÌ',
  'lo-trinh-tu-hoc': 'LỘ TRÌNH TU HỌC',
  'nep-song-thien-gia': 'NẾP SỐNG THIỀN GIA',
};

const fullArticles = [
  // 1. TIẾP BƯỚC THẦY TÔI
  existingMap[1] || {
    id: 1,
    slug: 'tiep-buoc-thay-toi',
    title: 'TIẾP BƯỚC THẦY TÔI',
    subtitle: 'Kính dâng bậc Ân sư khả kính – Sư Tổ Ngộ Chân Tử',
    category: 'tong-phong-truyen-thua',
    categoryName: 'TÔNG PHONG TRUYỀN THỪA',
    bannerImage: '/images/tong-chi/tong-chi-tu-hoc-tong-phong-truyen-thua-tiep-buoc-thay-toi-banner-thumnail.jpg',
    excerpt: 'Tập thơ và tư liệu lịch sử ghi dấu hành trình tiếp nối chí nguyện Sư Tổ Ngộ Chân Tử khai sơn chốn Tổ Hoằng Pháp.',
    content: parsedDocs['II_1_TRANG_CHI_TIET_TIEP_BUOC_THAY_TOI.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T08:00:00.000Z',
    status: 'published',
  },

  // 2. ĐỜI THẦY
  existingMap[2] || {
    id: 2,
    slug: 'tong-phong-truyen-thua-doi-thay',
    title: 'ĐỜI THẦY',
    subtitle: 'Kính dâng bậc Ân Sư Bổn Sư — Hòa Thượng Thích Chân Tính (Đại Sư Thanh Lương)',
    category: 'tong-phong-truyen-thua',
    categoryName: 'TÔNG PHONG TRUYỀN THỪA',
    bannerImage: '/images/tong-chi/tong-chi-tu-hoc-tong-phong-truyen-thua-bai-tho-doi-thay-thumbnail-herobanner.jpg',
    excerpt: 'Khắc họa chân dung giản dị, thanh cao và hạnh nguyện độ sinh cao cả của Hòa Thượng Thích Chân Tính.',
    content: parsedDocs['II_1_TRANG_CHI_TIET_DOI_THAY.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T08:30:00.000Z',
    status: 'published',
  },

  // 3. MIỀN NAM CHỐN TỔ
  {
    id: 3,
    slug: 'mien-nam-chon-to',
    title: 'MIỀN NAM CHỐN TỔ',
    subtitle: 'Hướng về Tổ Đình Hoằng Pháp & Tháp Tổ Nhị Nghiêm (Hóc Môn, TP.HCM)',
    category: 'tong-phong-truyen-thua',
    categoryName: 'TÔNG PHONG TRUYỀN THỪA',
    bannerImage: '/images/tong-chi/tong-chi-tu-hoc-tong-phong-truyen-thua-bai-tho-mien-nam-chon-to-thumbnail-herobanner.jpg',
    excerpt: 'Dòng hồi ức và bài thơ tri ân sâu sắc hướng về cội nguồn Tổ đình Hoằng Pháp nơi phương Nam đất ấm.',
    content: parsedDocs['II_1_TRANG_CHI_TIET_MIEN_NAM_CHON_TO.docx'] || `Đất trời Nam rạng ngời ánh đạo
Chốn Tổ đình Hoằng Pháp uy nghiêm
Sư Tổ xưa dốc lòng khai sáng
Độ muôn người thoát khỏi truân chuyên.

Tháp Nhị Nghiêm ngút ngàn mây trắng
Ghi ngàn thu công đức cao dày
Chúng con nay cúi đầu đãnh lễ
Nguyện một lòng tiếp bước theo thầy.`,
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T09:00:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'MIỀN NAM CHỐN TỔ — THÁP TỔ NHỊ NGHIÊM',
      subtitle: 'Kính bái Giác linh Sư Tổ Ngộ Chân Tử khai sáng chốn Tổ Hoằng Pháp',
      description: 'Thước phim tư liệu về chốn Tổ Hoằng Pháp và tháp Tổ Nhị Nghiêm ngút ngàn linh khí tại Hóc Môn, TP.HCM.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'TÔNG PHONG TRUYỀN THỪA',
      title: 'LỊCH SỬ KHAI SƠN TỔ ĐÌNH HOẰNG PHÁP VÀ VIỆN DỤC ANH',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/tong-chi-tu-hoc-tong-phong-hoang-phap-mien-nam-chon-to-thap-to-nhi-nghiem-popup.jpg',
      linkUrl: '/gioi-thieu/tieu-su-su-to',
    },
    photoGallery: [
      {
        title: 'THÁP TỔ NHỊ NGHIÊM',
        imageUrl: '/images/tong-chi/tong-chi-tu-hoc-tong-phong-hoang-phap-mien-nam-chon-to-thap-to-nhi-nghiem-popup.jpg',
        khuVuc: 'Tổ Đình Hoằng Pháp',
        noiDung: 'Bảo tháp nơi an nghỉ ngàn thu của Sư Tổ Ngộ Chân Tử tại Hóc Môn, TP.HCM.',
      },
      {
        title: 'CHÙA HOẰNG PHÁP KIẾN AN HẢI PHÒNG (1935)',
        imageUrl: '/images/tong-chi/su-to-tham-gio-hoc-cac-em-vien-duc-anh.jpg',
        khuVuc: 'Đất Bắc',
        noiDung: 'Sư Tổ Ngộ Chân Tử chăm lo đời sống giáo dục cho các em cô nhi tại Viện Dục Anh.',
      },
    ],
    sourceBook: {
      bookTitle: 'Đi Qua Khổ Vui Cuộc Đời',
      author: 'Sa Môn Vô Trí (hiệu Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/tong-chi-tu-hoc-tong-phong-truyen-thua-tiep-buoc-thay-toi-thay-chu-thich-popup-sach-dqkvcd.jpg',
      description: 'Ký ức đúc kết hành trình tu tập và tri ân các bậc tiền bối khai sáng Tông phong.',
      linkUrl: '/tri-tue-phat-phap/di-qua-kho-vui-cuoc-doi',
    },
    keywords: [
      {
        keyword: 'Chốn Tổ',
        title: 'TỔ ĐÌNH HOẰNG PHÁP (HÓC MÔN)',
        subtitle: 'CHỐN TỔ TÂM LINH CỦA HÀNG TRIỆU TÍN ĐỒ PHẬT TỬ',
        imageUrl: '/images/tong-chi/tong-chi-tu-hoc-tong-phong-hoang-phap-mien-nam-chon-to-thap-to-nhi-nghiem-popup.jpg',
        description: 'Tổ Đình Hoằng Pháp do Cố Đại Lão Hòa Thượng Ngộ Chân Tử khai sơn năm 1957 tại Hóc Môn, TP.HCM, là trung tâm tu học Phật thất lớn nhất cả nước.',
        linkUrl: 'https://chuahoangphap.com.vn',
      },
      {
        keyword: 'Tháp Tổ',
        title: 'THÁP TỔ NHỊ NGHIÊM',
        subtitle: 'NƠI LƯU GIỮ NHỤC THÂN VÀ LINH CỐT SƯ TỔ NGỘ CHÂN TỬ',
        imageUrl: '/images/tong-chi/tong-chi-tu-hoc-tong-phong-hoang-phap-mien-nam-chon-to-thap-to-nhi-nghiem-popup.jpg',
        description: 'Bảo tháp Nhị Nghiêm được tôn tạo trang nghiêm trong khuôn viên Chùa Hoằng Pháp, nơi hàng triệu con tim hậu học hướng về đảnh lễ tri ân.',
        linkUrl: '/gioi-thieu/tieu-su-su-to',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 4. BỒ ĐỀ TÂM — CỘI NGUỒN THIỆN PHÁP
  {
    id: 4,
    slug: 'bo-de-tam-coi-nguon-thien-phap',
    title: 'BỒ ĐỀ TÂM — CỘI NGUỒN MỌI THIỆN PHÁP',
    subtitle: 'Nền tảng khởi đầu và động lực tối thượng trên lộ trình giác ngộ',
    category: 'nen-tang-tu-hoc',
    categoryName: 'NỀN TẢNG TU HỌC',
    bannerImage: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-bo-de-tam-herobanner-thumbnail.jpg',
    excerpt: 'Tâm Bồ Đề là hạt giống giác ngộ, là cội nguồn phát sinh muôn vàn công đức và thiện hạnh của người con Phật.',
    content: parsedDocs['II_2_1_BO_DE_TAM.docx'] || parsedDocs['TRANG CHI TIẾT - BỒ ĐỀ TÂM.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T09:10:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'PHÁP THOẠI: PHÁT KHỞI BỒ ĐỀ TÂM',
      subtitle: 'Khơi dậy ngọn đèn trí tuệ và tình thương vô ngã',
      description: 'Bài giảng sâu sắc về tầm quan trọng của Tâm Bồ Đề trong đời sống tu học và phụng sự nhân sinh.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'NỀN TẢNG TU HỌC',
      title: 'BỒ ĐỀ TÂM LUẬN — TINH HOA GIÁO NGHĨA PHẬT GIÁO ĐẠI THỪA',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-bo-de-tam-banner-sach.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'BỒ ĐỀ TÂM BIỂU TƯỢNG',
        imageUrl: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-bo-de-tam-herobanner-thumbnail.jpg',
        khuVuc: 'Chánh Điện',
        noiDung: 'Ánh sáng Bồ Đề soi rọi muôn phương, dẫn dắt chúng sinh quay về bến giác.',
      },
      {
        title: 'TẬP SÁCH BỒ ĐỀ TÂM',
        imageUrl: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-bo-de-tam-banner-sach.jpg',
        khuVuc: 'Tàng Kinh Các',
        noiDung: 'Tài liệu hướng dẫn phát nguyện và nuôi dưỡng tâm Bồ Đề mỗi ngày.',
      },
    ],
    sourceBook: {
      bookTitle: 'Nền Tảng Tu Học — Sách Bồ Đề Tâm',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-bo-de-tam-banner-sach.jpg',
      description: 'Cẩm nang căn bản giải thích tường tận về ý nghĩa, phân loại và cách thức nuôi dưỡng tâm Bồ Đề.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Bồ Đề Tâm',
        title: 'BỒ ĐỀ TÂM (BODHICITTA)',
        subtitle: 'TÂM NGUYỆN CẦU THÀNH PHẬT ĐỂ ĐỘ TẬN CHÚNG SINH',
        imageUrl: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-bo-de-tam-herobanner-thumbnail.jpg',
        description: 'Bồ Đề Tâm là tâm nguyện giác ngộ tối thượng, gồm Đại Bi tâm và Đại Trí tuệ, là nền tảng cốt tủy của mọi pháp môn tu hành.',
        linkUrl: '/gioi-thieu/lich-su-tung-lam-hoa-phuc',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 5. TAM QUY NGŨ GIỚI
  {
    id: 5,
    slug: 'tam-quy-ngu-gioi-nen-tang-nguoi-phat-tu',
    title: 'TAM QUY NGŨ GIỚI — NỀN TẢNG NGƯỜI PHẬT TỬ',
    subtitle: 'Nấc thang đầu tiên bước vào ngôi nhà Phật pháp và giữ gìn nhân cách an lành',
    category: 'nen-tang-tu-hoc',
    categoryName: 'NỀN TẢNG TU HỌC',
    bannerImage: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-tam-quy-ngu-gioi-hero-banner-thumnail.jpg',
    excerpt: 'Quy y Tam Bảo và thọ trì Năm Giới là kim chỉ nam bảo vệ người con Phật khỏi những nẻo đường tăm tối, xây dựng đời sống hạnh phúc.',
    content: parsedDocs['II_2_2_TRANG_CHI_TIET_TAM_QUY_NGU_GIOI.docx'] || parsedDocs['II_2_2_TAM_QUY.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T09:20:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'Ý NGHĨA QUY Y TAM BẢO VÀ NĂM GIỚI',
      subtitle: 'Hàng rào đạo đức che chở cho sự bình an tự thân và gia đình',
      description: 'Khai thị cặn kẽ về Tam Quy (Phật, Pháp, Tăng) và Ngũ Giới (Không sát sinh, trộm cắp, tà dâm, nói dối, say sưa).',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'NỀN TẢNG TU HỌC',
      title: 'TAM QUY NGŨ GIỚI — CHIẾC ÁO GIÁP BẢO VỆ NGƯỜI PHẬT TỬ TẠI GIA',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/anh-minh-hoa-tam-quy-ngu-gioi.png',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'ĐẠI LỄ QUY Y TAM BẢO',
        imageUrl: '/images/tong-chi/anh-minh-hoa-tam-quy-ngu-gioi.png',
        khuVuc: 'Chánh Điện Tùng Lâm Hòa Phúc',
        noiDung: 'Hàng ngàn thiện nam tín nữ trang nghiêm phát nguyện thọ trì Tam Quy Ngũ Giới.',
      },
    ],
    sourceBook: {
      bookTitle: 'Nền Tảng Tu Học — Tam Quy & Ngũ Giới',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-tam-quy-ngu-gioi-banner-sach-3-nt-5-th.jpg.jpg',
      description: 'Sách chỉ dẫn tường tận cách giữ giới và chuyển hóa nghiệp chướng trong đời sống thường nhật.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Tam Quy',
        title: 'TAM QUY (QUY Y TAM BẢO)',
        subtitle: 'QUY Y PHẬT — QUY Y PHÁP — QUY Y TĂNG',
        imageUrl: '/images/tong-chi/anh-minh-hoa-tam-quy-ngu-gioi.png',
        description: 'Tam Quy là quay về nương tựa ba ngôi báu: Phật (bậc giác ngộ), Pháp (con đường chân lý), Tăng (đoàn thể thanh tịnh hòa hợp).',
        linkUrl: '/gioi-thieu/su-phu-tru-tri',
      },
      {
        keyword: 'Ngũ Giới',
        title: 'NGŨ GIỚI CĂN BẢN',
        subtitle: 'NĂM ĐIỀU ĐẠO ĐỨC BẢO VỆ PHẨM GIÁ CON NGƯỜI',
        imageUrl: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-tam-quy-ngu-gioi-hero-banner-thumnail.jpg',
        description: 'Năm giới gồm: Không sát sinh, Không trộm cắp, Không tà dâm, Không nói dối, Không sử dụng các chất gây say nghiện làm mất chánh niệm.',
        linkUrl: '/gioi-thieu/van-hoa-ung-xu',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 6. THẬP THIỆN NGHIỆP
  {
    id: 6,
    slug: 'thap-thien-nghiep-con-duong-phuoc-duc',
    title: 'THẬP THIỆN NGHIỆP — CON ĐƯỜNG PHƯỚC ĐỨC & AN LẠC',
    subtitle: 'Mười việc lành chuyển hóa ba nghiệp Thân – Khẩu – Ý thanh tịnh',
    category: 'nen-tang-tu-hoc',
    categoryName: 'NỀN TẢNG TU HỌC',
    bannerImage: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-thap-thien-thumbnail-herobanner.jpg',
    excerpt: 'Thực hành mười điều lành giúp mở rộng phước báu nhân thiên và kiến tạo nền tảng vững chắc cho sự giải thoát rốt ráo.',
    content: parsedDocs['II_2_3_TRANG_CHI_TIET_THAP_THIEN.docx'] || parsedDocs['II_2_3_THAP_THIEN.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T09:30:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'KINH THẬP THIỆN NGHIỆP ĐẠO DIỄN GIẢI',
      subtitle: 'Con đường kiến tạo hạnh phúc nhân thiên và giải thoát',
      description: 'Pháp âm giảng giải chi tiết về 10 nghiệp lành nơi Thân (3), Miệng (4), Ý (3).',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'NỀN TẢNG TU HỌC',
      title: 'THẬP THIỆN NGHIỆP — NỀN TẢNG CỦA CÕI TRỜI VÀ CÕI PHẬT',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/thap-thien-gioi.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'THẬP THIỆN NGHIỆP GIẢNG GIẢI',
        imageUrl: '/images/tong-chi/thap-thien-gioi.jpg',
        khuVuc: 'Giảng Đường Tùng Lâm Hòa Phúc',
        noiDung: 'Đại chúng lắng nghe khai thị về mười điều thiện chuyển hóa ba nghiệp.',
      },
    ],
    sourceBook: {
      bookTitle: 'Nền Tảng Tu Học — Thập Thiện Nghiệp',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-thap-thien-thumbnail-herobanner.jpg',
      description: 'Tài liệu hướng dẫn tu sửa thân khẩu ý hằng ngày.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Thập Thiện',
        title: 'THẬP THIỆN NGHIỆP ĐẠO',
        subtitle: '10 HÀNH ĐỘNG THIỆN LÀNH NƠI THÂN, KHẨU, Ý',
        imageUrl: '/images/tong-chi/thap-thien-gioi.jpg',
        description: 'Thân ba (không sát sinh, không trộm cắp, không tà dâm); Miệng bốn (không nói dối, không nói lời thêu dệt, không nói hai lưỡi, không nói lời ác độc); Ý ba (không tham lam, không sân hận, không tà kiến).',
        linkUrl: '/gioi-thieu/van-hoa-ung-xu',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 7. BỒ TÁT HẠNH — LỤC ĐỘ BA LA MẬT
  {
    id: 7,
    slug: 'bo-tat-hanh-luc-do-ba-la-mat',
    title: 'BỒ TÁT HẠNH — LỤC ĐỘ BA LA MẬT',
    subtitle: 'Sáu pháp tu vi diệu đưa người con Phật từ bờ mê sang bến giác',
    category: 'nen-tang-tu-hoc',
    categoryName: 'NỀN TẢNG TU HỌC',
    bannerImage: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-bo-tat-hanh-luc-do-van-hanh-banner-thumbnail.jpg',
    excerpt: 'Lục Độ gồm: Bố Thí, Trì Giới, Nhẫn Nhục, Tinh Tấn, Thiền Định, Trí Tuệ — là hành trang cứu cánh viên thành Phật quả.',
    content: parsedDocs['II_2_4_BO_TAT_HANH.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T09:40:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'HẠNH NGUYỆN BỒ TÁT TRONG ĐỜI SỐNG HIỆN ĐẠI',
      subtitle: 'Dấn thân phụng sự chúng sinh không mệt mỏi',
      description: 'Pháp thoại về hạnh nguyện độ tha của chư Bồ Tát và cách áp dụng Lục Độ trong cuộc sống.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'NỀN TẢNG TU HỌC',
      title: 'BỒ TÁT HẠNH — LỤC ĐỘ VẠN HẠNH ĐỘ TẬN CHÚNG SINH',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/bo-tat-chuan-de-bieu-tuong-luc-do-van-hanh.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'BỒ TÁT CHUẨN ĐỀ BIỂU TƯỢNG LỤC ĐỘ VẠN HẠNH',
        imageUrl: '/images/tong-chi/bo-tat-chuan-de-bieu-tuong-luc-do-van-hanh.jpg',
        khuVuc: 'Chánh Điện Hòa Phúc',
        noiDung: 'Bức tôn tượng biểu trưng cho muôn vàn hạnh nguyện độ sinh nhiệm màu.',
      },
    ],
    sourceBook: {
      bookTitle: 'Nền Tảng Tu Học — Sách Bồ Tát Hạnh Lục Độ Ba La Mật',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/tong-chi-tu-hoc-nen-tang-tu-hoc-bo-tat-hanh-luc-do-van-hanh-banner-thumbnail.jpg',
      description: 'Luận giải chi tiết về sáu hạnh Ba La Mật cứu cánh.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Lục Độ',
        title: 'LỤC ĐỘ BA LA MẬT (PARAMITA)',
        subtitle: 'SÁU PHÁP ĐỘ ĐƯA QUA BỜ GIÁC AN VUI',
        imageUrl: '/images/tong-chi/bo-tat-chuan-de-bieu-tuong-luc-do-van-hanh.jpg',
        description: '1. Bố thí độ bủn xỉn; 2. Trì giới độ phá giới; 3. Nhẫn nhục độ sân hận; 4. Tinh tấn độ biếng nhác; 5. Thiền định độ tán loạn; 6. Trí tuệ độ si mê.',
        linkUrl: '/tri-tue-phat-phap',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 8. NIỆM PHẬT
  {
    id: 8,
    slug: 'niem-phat-phuong-phap-tro-hanh',
    title: 'NIỆM PHẬT — PHƯƠNG PHÁP TRỢ HẠNH VÃNG SANH',
    subtitle: 'Nương tựa hồng danh đức Phật A Di Đà để nhiếp tâm thanh tịnh',
    category: 'phuong-phap-hanh-tri',
    categoryName: 'PHƯƠNG PHÁP HÀNH TRÌ',
    bannerImage: '/images/tong-chi/niem-phat.jpg',
    excerpt: 'Niệm Phật là pháp môn thù thắng, dung dị mà sâu mầu, giúp hành giả an định tâm trí giữa muôn ngàn biến động trần lao.',
    content: parsedDocs['II_3_1_NIEM_PHAT.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T09:50:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'KHÓA LỄ NIỆM PHẬT KINH HÀNH TÙNG LÂM HÒA PHÚC',
      subtitle: 'Từng bước chân an lạc, từng tiếng niệm Di Đà',
      description: 'Video hướng dẫn tư thế kinh hành niệm Phật và phương pháp nhiếp tâm trong từng hơi thở.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'PHƯƠNG PHÁP HÀNH TRÌ',
      title: 'PHÁP MÔN NIỆM PHẬT — CON ĐƯỜNG TẮT VƯỢT THOÁT LUÂN HỒI',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/niem-phat.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'HÀNH GIẢ TỊNH ĐỘ TRANG NGHIÊM',
        imageUrl: '/images/tong-chi/niem-phat.jpg',
        khuVuc: 'Chánh Điện Hòa Phúc',
        noiDung: 'Đại chúng chí thành trì niệm danh hiệu Phật A Di Đà.',
      },
    ],
    sourceBook: {
      bookTitle: 'Phương Pháp Hành Trì — Niệm Phật & Tịnh Độ',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/niem-phat.jpg',
      description: 'Hướng dẫn pháp hành Niệm Phật thực tế cho người Phật tử.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Niệm Phật',
        title: 'PHÁP MÔN TRÌ DANH NIỆM PHẬT',
        subtitle: 'NAM MÔ A DI ĐÀ PHẬT',
        imageUrl: '/images/tong-chi/niem-phat.jpg',
        description: 'Tâm tưởng Phật, miệng niệm Phật, thân kính Phật. Lấy Tín - Nguyện - Hạnh làm tư lương vãng sanh Cực Lạc.',
        linkUrl: '/tri-tue-phat-phap',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 9. TỤNG KINH
  {
    id: 9,
    slug: 'tung-kinh-soi-sang-tri-tue',
    title: 'TỤNG KINH — SOI SÁNG TRÍ TUỆ & ĐỊNH TÂM',
    subtitle: 'Đọc tụng lời vàng của Đức Thế Tôn để thấu triệt chánh pháp',
    category: 'phuong-phap-hanh-tri',
    categoryName: 'PHƯƠNG PHÁP HÀNH TRÌ',
    bannerImage: '/images/tong-chi/tung-kinh.jpg',
    excerpt: 'Tụng kinh không phải để cầu xin mà là cơ hội ôn lại lời Phật dạy, soi rọi lại tâm mình và nuôi dưỡng sự an lạc.',
    content: parsedDocs['II_3_2_TUNG_KINH.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T10:00:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'KHÓA TỤNG KINH DƯỢC SƯ CẦU AN',
      subtitle: 'Âm thanh vi diệu xua tan phiền não thế gian',
      description: 'Khóa lễ tụng kinh trang nghiêm tại Đạo tràng Tùng Lâm Hòa Phúc.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'PHƯƠNG PHÁP HÀNH TRÌ',
      title: 'Ý NGHĨA CHÂN THẬT CỦA VIỆC TỤNG KINH BÁI SÁM',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/tung-kinh.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'ĐẠI CHÚNG TRANG NGHIÊM TỤNG KINH',
        imageUrl: '/images/tong-chi/tung-kinh.jpg',
        khuVuc: 'Chánh Điện Tam Bảo',
        noiDung: 'Tiếng chuông mõ hòa cùng lời kinh vang vọng khắp thiền môn.',
      },
    ],
    sourceBook: {
      bookTitle: 'Kinh Kệ Nhật Tụng Tùng Lâm Hòa Phúc',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/tung-kinh.jpg',
      description: 'Tuyển tập các thời kinh khóa tụng hàng ngày.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Tụng Kinh',
        title: 'NGHI THỨC TỤNG KINH',
        subtitle: 'THÂN TRANG NGHIÊM — MIỆNG ĐỌC TỤNG — Ý THẤU HIỂU',
        imageUrl: '/images/tong-chi/tung-kinh.jpg',
        description: 'Tụng kinh là phương tiện chuyển hóa tâm thức, giúp tâm định tĩnh và trí tuệ phát sinh.',
        linkUrl: '/tri-tue-phat-phap',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 10. THIỀN TẬP
  {
    id: 10,
    slug: 'thien-tap-tinh-lang-tu-than',
    title: 'THIỀN TẬP — TÌM LẠI SỰ TĨNH LẶNG TỰ THÂN',
    subtitle: 'Trở về quan sát hơi thở và an trú trong giây phút hiện tại',
    category: 'phuong-phap-hanh-tri',
    categoryName: 'PHƯƠNG PHÁP HÀNH TRÌ',
    bannerImage: '/images/tong-chi/thien-toa.jpg',
    excerpt: 'Thiền tập giúp xoa dịu những căng thẳng, đưa tâm thức trở về trạng thái trong sáng, định tĩnh và tự do.',
    content: parsedDocs['II_3_3_THIEN_TAP.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T10:10:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'HƯỚNG DẪN TỌA THIỀN VÀ QUAN SÁT HƠI THỞ',
      subtitle: 'Thả lỏng toàn thân, an trú hiện tại',
      description: 'Các bước điều thân, điều tức, điều tâm căn bản cho hành giả mới bắt đầu.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'PHƯƠNG PHÁP HÀNH TRÌ',
      title: 'THIỀN TRONG ĐỜI SỐNG — HƠI THỞ VÀ NỤ CƯỜI TỈNH THỨC',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/thien-toa.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'GIỜ THIỀN TỌA TĨNH LẶNG',
        imageUrl: '/images/tong-chi/thien-toa.jpg',
        khuVuc: 'Thiền Đường Tùng Lâm Hòa Phúc',
        noiDung: 'Không gian tĩnh mịch giúp hành giả lắng đọng mọi tạp niệm.',
      },
    ],
    sourceBook: {
      bookTitle: 'Cẩm Nang Thiền Tập Ứng Dụng',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/thien-toa.jpg',
      description: 'Phương pháp thực hành thiền tọa và thiền hành giữa đời sống bận rộn.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Thiền Tập',
        title: 'THIỀN ĐỊNH (MEDITATION)',
        subtitle: 'AN TRÚ TRONG GIÂY PHÚT HIỆN TẠI',
        imageUrl: '/images/tong-chi/thien-toa.jpg',
        description: 'Thiền là sự có mặt trọn vẹn, nhận biết rõ ràng mọi diễn biến của thân và tâm mà không phán xét.',
        linkUrl: '/gioi-thieu/van-hoa-ung-xu',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 11. LẠY PHẬT
  {
    id: 11,
    slug: 'lay-phat-tieu-tru-ban-nga',
    title: 'LẠY PHẬT — TIÊU TRỪ BẢN NGÃ & NGHIỆP CHƯỚNG',
    subtitle: 'Năm vóc sát đất, phủ phục trước bậc Đại Giác để gột rửa tâm kiêu mạn',
    category: 'phuong-phap-hanh-tri',
    categoryName: 'PHƯƠNG PHÁP HÀNH TRÌ',
    bannerImage: '/images/tong-chi/1.jpg',
    excerpt: 'Đảnh lễ Đức Phật với tâm thành kính tuyệt đối là phương thuốc màu nhiệm chữa lành tâm kiêu ngạo và tiêu trừ nghiệp chướng nhiều đời.',
    content: parsedDocs['II_3_4_LAY_PHAT.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T10:20:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'HƯỚNG DẪN OAI NGHI LẠY PHẬT ĐÚNG CHÁNH PHÁP',
      subtitle: 'Ngũ thể đầu địa — Tiêu trừ bản ngã',
      description: 'Khai thị về phương pháp lạy Phật rèn luyện sức khỏe thể chất và nuôi dưỡng tâm khiêm hạ.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'PHƯƠNG PHÁP HÀNH TRÌ',
      title: 'CÔNG ĐỨC LẠY PHẬT VÀ SỰ CHUYỂN HÓA THÂN TÂM',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/1.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'HÀNH GIẢ CHÍ THÀNH ĐẢNH LỄ TAM BẢO',
        imageUrl: '/images/tong-chi/1.jpg',
        khuVuc: 'Chánh Điện Hòa Phúc',
        noiDung: 'Mỗi cái lạy là một lần cúi đầu buông bỏ bản ngã phàm phu.',
      },
    ],
    sourceBook: {
      bookTitle: 'Nghi Thức Lạy Phật Sám Hối',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/1.jpg',
      description: 'Chỉ dẫn chi tiết nghi thức lễ bái tam bảo.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Lạy Phật',
        title: 'NGŨ THỂ ĐẦU ĐỊA (LẠY PHẬT)',
        subtitle: 'HAI TAY, HAI ĐẦU GỐI VÀ TRÁN CHẠM ĐẤT',
        imageUrl: '/images/tong-chi/1.jpg',
        description: 'Cử chỉ chí kính biểu thị sự quy phục hoàn toàn trước trí tuệ và từ bi của chư Phật, dứt trừ tâm ngạo mạn.',
        linkUrl: '/gioi-thieu/van-hoa-ung-xu',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 12. SÁM HỐI
  {
    id: 12,
    slug: 'sam-hoi-tinh-hoa-than-tam',
    title: 'SÁM HỐI — TỊNH HÓA THÂN TÂM',
    subtitle: 'Ăn năn lỗi trước, nguyện không tái phạm lỗi sau để làm mới chính mình',
    category: 'phuong-phap-hanh-tri',
    categoryName: 'PHƯƠNG PHÁP HÀNH TRÌ',
    bannerImage: '/images/tong-chi/594929082-1281299250704762-2908984688896417320-n.jpg',
    excerpt: 'Sám hối là dòng nước mát gột rửa mọi bùn nhơ tội lỗi, giúp tâm hồn thanh thản và mở ra con đường tái sinh phẩm hạnh.',
    content: parsedDocs['II_3_5_SAM_HOI.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T10:30:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'KHÓA LỄ LƯƠNG HOÀNG BẢO SÁM',
      subtitle: 'Giải tỏa oan khiên, tiêu trừ túc nghiệp',
      description: 'Ý nghĩa của sự sám hối chân thật và các khóa lễ bái sám chuyển hóa nghiệp lực tại chùa.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'PHƯƠNG PHÁP HÀNH TRÌ',
      title: 'SÁM HỐI — BƯỚC ĐẦU TIÊN CỦA SỰ THỨC TỈNH VÀ CHUYỂN NGHIỆP',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/594929082-1281299250704762-2908984688896417320-n.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'ĐẠI LỄ SÁM HỐI ĐỊNH KỲ',
        imageUrl: '/images/tong-chi/594929082-1281299250704762-2908984688896417320-n.jpg',
        khuVuc: 'Chánh Điện Hòa Phúc',
        noiDung: 'Đại chúng quỳ trước Tam Bảo chí thành bày tỏ lỗi lầm.',
      },
    ],
    sourceBook: {
      bookTitle: 'Nghi Thức Hồng Danh Sám Hối',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/594929082-1281299250704762-2908984688896417320-n.jpg',
      description: 'Tuyển tập văn sám hối và 88 vị Phật.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Sám Hối',
        title: 'SÁM HỐI CHÂN THẬT',
        subtitle: 'SÁM DÃ HỐI KỲ TIỀN KHIÊN — HỐI DÃ PHÒNG KỲ HẬU QUÁ',
        imageUrl: '/images/tong-chi/594929082-1281299250704762-2908984688896417320-n.jpg',
        description: 'Ăn năn lỗi cũ và thệ nguyện từ nay về sau không tái phạm, giữ tâm thanh tịnh hướng thiện.',
        linkUrl: '/tri-tue-phat-phap',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 13. NGHE PHÁP
  {
    id: 13,
    slug: 'nghe-phap-khai-mo-chanh-kien',
    title: 'NGHE PHÁP — KHAI MỞ CHÁNH KIẾN',
    subtitle: 'Tiếp nhận giáo lý chân chính để xua tan màn đêm vô minh',
    category: 'phuong-phap-hanh-tri',
    categoryName: 'PHƯƠNG PHÁP HÀNH TRÌ',
    bannerImage: '/images/tong-chi/nghe-phap.png',
    excerpt: 'Nghe pháp là nấc thang Văn trong tiến trình Văn – Tư – Tu, giúp người học Phật hiểu đúng chân lý và không bị lạc vào tà kiến.',
    content: parsedDocs['II_3_6_NGHE_PHAP.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T10:40:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'NGHE PHÁP NHƯ THẾ NÀO CHO ĐÚNG CHÁNH ĐẠO?',
      subtitle: 'Lắng nghe với tâm cung kính và không thiên kiến',
      description: 'Bài giảng chỉ dẫn thái độ đúng đắn khi đón nhận Phật pháp để chuyển hóa tri kiến.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'PHƯƠNG PHÁP HÀNH TRÌ',
      title: 'VĂN TƯ TU — BA BẬC TRÍ TUỆ GIẢI THOÁT',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/nghe-phap.png',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'HÀNG NGÀN PHẬT TỬ CHĂM CHÚ NGHE PHÁP',
        imageUrl: '/images/tong-chi/nghe-phap.png',
        khuVuc: 'Giảng Đường Tùng Lâm Hòa Phúc',
        noiDung: 'Pháp hội hoằng pháp trang nghiêm dưới sự giảng dạy của chư Tôn đức.',
      },
    ],
    sourceBook: {
      bookTitle: 'Pháp Âm Tùng Lâm — Tuyển Tập Giảng Giải',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/nghe-phap.png',
      description: 'Tổng hợp các bài giảng pháp căn bản cho Phật tử.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Nghe Pháp',
        title: 'THÍNH PHÁP (NGHE PHÁP)',
        subtitle: 'CỬA NGÕ MỞ RA TRÍ TUỆ BÁT NHÃ',
        imageUrl: '/images/tong-chi/nghe-phap.png',
        description: 'Lắng nghe bằng tâm thanh tịnh, tư duy sâu sắc để thấu suốt lý nhân quả và bản chất vô ngã của vạn pháp.',
        linkUrl: '/tri-tue-phat-phap',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 14. PHỤNG SỰ
  {
    id: 14,
    slug: 'phung-su-tot-doi-dep-dao',
    title: 'PHỤNG SỰ — TỐT ĐỜI ĐẸP ĐẠO',
    subtitle: 'Đem công sức và tâm huyết cống hiến cho Tam Bảo và tha nhân',
    category: 'phuong-phap-hanh-tri',
    categoryName: 'PHƯƠNG PHÁP HÀNH TRÌ',
    bannerImage: '/images/tong-chi/bon-phan-nguoi-phat-tu-tai-gia.jpg',
    excerpt: 'Phụng sự chúng sinh là cúng dường chư Phật. Làm công quả tại chốn già lam giúp tôi luyện đức tính khiêm nhường và bồi đắp phúc báu sâu dày.',
    content: parsedDocs['II_3_7_PHUNG_SU.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T10:50:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'TINH THẦN PHỤNG SỰ CỦA NGƯỜI PHẬT TỬ',
      subtitle: 'Lao động là vinh quang — Công quả là gieo phúc',
      description: 'Hình ảnh Phật tử hoan hỷ chấp tác, nấu nướng, dọn dẹp phụng sự các khóa tu hàng vạn người.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'PHƯƠNG PHÁP HÀNH TRÌ',
      title: 'CÔNG QUẢ VÀ HẠNH NGUYỆN PHỤNG SỰ TẠI THIỀN MÔN',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/bon-phan-nguoi-phat-tu-tai-gia.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'PHẬT TỬ CHẤP TÁC PHỤNG SỰ KHÓA TU',
        imageUrl: '/images/tong-chi/bon-phan-nguoi-phat-tu-tai-gia.jpg',
        khuVuc: 'Khu Nhà Bếp & Trai Đường',
        noiDung: 'Mỗi món ăn, mỗi chén nước trao đi đều gói trọn tình thương và tâm hộ trì đạo pháp.',
      },
    ],
    sourceBook: {
      bookTitle: 'Nếp Sống Phụng Sự Thiền Môn',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/bon-phan-nguoi-phat-tu-tai-gia.jpg',
      description: 'Cẩm nang công quả và trách nhiệm người Phật tử.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Phụng Sự',
        title: 'HẠNH PHỤNG SỰ CHÚNG SINH',
        subtitle: 'PHỤNG SỰ CHÚNG SINH LÀ CÚNG DƯỜNG CHƯ PHẬT',
        imageUrl: '/images/tong-chi/bon-phan-nguoi-phat-tu-tai-gia.jpg',
        description: 'Tự nguyện dấn thân đóng góp công sức, trí tuệ vì sự hưng thịnh của Tam Bảo và lợi ích cộng đồng.',
        linkUrl: '/gioi-thieu/van-hoa-ung-xu',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 15. BỐ THÍ CÚNG DƯỜNG
  {
    id: 15,
    slug: 'bo-thi-cung-duong-nuoi-lon-phuc-bau',
    title: 'BỐ THÍ CÚNG DƯỜNG — NUÔI LỚN PHÚC BÁU',
    subtitle: 'Mở rộng bàn tay san sẻ tài vật, giáo pháp và sự không sợ hãi cho muôn loài',
    category: 'phuong-phap-hanh-tri',
    categoryName: 'PHƯƠNG PHÁP HÀNH TRÌ',
    bannerImage: '/images/tong-chi/bo-thi-cung-duong.jpg',
    excerpt: 'Bố thí là phương pháp xả ly lòng bỏn xẻn tham lam, kiến tạo phúc điền nhân quả thù thắng cho đời này và muôn đời sau.',
    content: parsedDocs['II_3_8_BO_THI_CUNG_DUONG.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T11:00:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'BA PHƯƠNG PHÁP BỐ THÍ THÙ THẮNG: TÀI THÍ - PHÁP THÍ - VÔ ÚY THÍ',
      subtitle: 'Gieo hạt mầm phúc báu cho đời',
      description: 'Pháp thoại khai thị về tâm thái cho đi thanh tịnh (Tam luân không tịch) không cầu danh lợi báo đáp.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'PHƯƠNG PHÁP HÀNH TRÌ',
      title: 'BỐ THÍ BA LA MẬT — TAM LUÂN THỂ KHÔNG TRONG ĐỜI SỐNG',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/bo-thi-cung-duong.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'ĐẠI LỄ ĐẶT BÁT CÚNG DƯỜNG CHƯ TĂNG',
        imageUrl: '/images/tong-chi/bo-thi-cung-duong.jpg',
        khuVuc: 'Khuôn Viên Tùng Lâm Hòa Phúc',
        noiDung: 'Hàng ngàn Phật tử chí thành dâng cúng tịnh tài tịnh vật gieo trồng ruộng phước.',
      },
    ],
    sourceBook: {
      bookTitle: 'Nghệ Thuật Bố Thí & Cúng Dường',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/bo-thi-cung-duong.jpg',
      description: 'Chỉ dẫn tâm thế đúng đắn khi làm thiện nguyện cúng dường.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Bố Thí',
        title: 'BỐ THÍ BA LA MẬT (DANA)',
        subtitle: 'TÀI THÍ — PHÁP THÍ — VÔ ÚY THÍ',
        imageUrl: '/images/tong-chi/bo-thi-cung-duong.jpg',
        description: 'Tài thí sẻ chia vật chất; Pháp thí sẻ chia chân lý Phật; Vô úy thí đem lại sự bình an, không sợ hãi cho chúng sinh.',
        linkUrl: '/tri-tue-phat-phap',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 16. LỘ TRÌNH CHO NGƯỜI MỚI BẮT ĐẦU
  {
    id: 16,
    slug: 'lo-trinh-tu-hoc-nguoi-moi-bat-dau',
    title: 'LỘ TRÌNH TU HỌC DÀNH CHO NGƯỜI MỚI BẮT ĐẦU',
    subtitle: 'Từng bước xây dựng nền tảng chánh kiến và thực hành đạo đức căn bản',
    category: 'lo-trinh-tu-hoc',
    categoryName: 'LỘ TRÌNH TU HỌC',
    bannerImage: '/images/tong-chi/lo-trinh-danh-cho-nguoi-moi-bat-dau.jpg',
    excerpt: 'Hướng dẫn lộ trình từng bậc giúp người sơ cơ dễ dàng tiếp cận giáo lý Phật đà mà không bị ngợp hay lạc hướng.',
    content: parsedDocs['II_4_1_LT_NGUOI_MOI.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T11:10:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'NHỮNG ĐIỀU NGƯỜI MỚI HỌC PHẬT CẦN BIẾT',
      subtitle: 'Khởi tâm đúng — Học hỏi đúng — Thực hành đúng',
      description: 'Lộ trình 5 bước: Khởi tâm ➔ Học hỏi ➔ Thực hành ➔ Kiên trì ➔ Chuyển hóa.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'LỘ TRÌNH TU HỌC',
      title: 'BA CỘT TRỤ CỦA NGƯỜI HỌC PHẬT: LAO ĐỘNG – TU HỌC – HÀNH TRÌ',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/lo-trinh-danh-cho-nguoi-moi-bat-dau.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'KHÓA TU DÀNH CHO PHẬT TỬ SƠ CƠ',
        imageUrl: '/images/tong-chi/lo-trinh-danh-cho-nguoi-moi-bat-dau.jpg',
        khuVuc: 'Chánh Điện Hòa Phúc',
        noiDung: 'Được chư Tăng chỉ dạy từng cử chỉ lạy Phật, xá chào và cách xưng hô trong chùa.',
      },
    ],
    sourceBook: {
      bookTitle: 'Cẩm Nang Người Mới Học Phật',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/lo-trinh-danh-cho-nguoi-moi-bat-dau.jpg',
      description: 'Sách hướng dẫn vỡ lòng dành cho tân thiện nam tín nữ.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Người mới',
        title: 'LỘ TRÌNH 5 BƯỚC CHO NGƯỜI MỚI',
        subtitle: 'KHỞI TÂM ➔ HỌC HỎI ➔ THỰC HÀNH ➔ KIÊN TRÌ ➔ CHUYỂN HÓA',
        imageUrl: '/images/tong-chi/lo-trinh-danh-cho-nguoi-moi-bat-dau.jpg',
        description: 'Từng bước tiếp cận từ Quy Y, Giữ Giới cho đến Lễ Phật, Tụng Kinh và Tọa Thiền.',
        linkUrl: '/gioi-thieu/van-hoa-ung-xu',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 17. LỘ TRÌNH CHO NGƯỜI TRẺ
  {
    id: 17,
    slug: 'lo-trinh-tu-hoc-nguoi-tre',
    title: 'LỘ TRÌNH TU HỌC DÀNH CHO NGƯỜI TRẺ',
    subtitle: 'Nuôi dưỡng lý tưởng sống cao đẹp, rèn luyện nhân cách và phụng sự cộng đồng',
    category: 'lo-trinh-tu-hoc',
    categoryName: 'LỘ TRÌNH TU HỌC',
    bannerImage: '/images/tong-chi/lo-trinh-danh-cho-nguoi-tre.jpg',
    excerpt: 'Tuổi trẻ là mùa xuân của cuộc đời; ứng dụng Phật pháp giúp người trẻ xây dựng điểm tựa tâm linh vững chắc giữa sóng gió thời đại.',
    content: parsedDocs['II_4_2_LT_NGUOI_TRE.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T11:20:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'KHÓA TU MÙA HÈ DÀNH CHO THANH THIẾU NIÊN TÙNG LÂM HÒA PHÚC',
      subtitle: 'Tuổi trẻ sống đẹp — Sống có lý tưởng và lòng tri ân',
      description: 'Thước phim tư liệu về các hoạt động rèn luyện kỹ năng, đạo đức và hiếu thảo của hàng ngàn bạn trẻ tại chùa.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'LỘ TRÌNH TU HỌC',
      title: 'CÓ LÝ TƯỞNG ĐỂ KHÔNG LẠC HƯỚNG — THÔNG ĐIỆP GỬI NGƯỜI TRẺ',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/lo-trinh-danh-cho-nguoi-tre.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'HÀNG NGÀN BẠN TRẺ THAM DỰ KHÓA TU',
        imageUrl: '/images/tong-chi/lo-trinh-danh-cho-nguoi-tre.jpg',
        khuVuc: 'Quảng Trường Tùng Lâm Hòa Phúc',
        noiDung: 'Nụ cười rạng rỡ của tuổi trẻ trong tinh thần hòa hợp và phụng sự.',
      },
    ],
    sourceBook: {
      bookTitle: 'Tuổi Trẻ & Lý Tưởng Học Phật',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/lo-trinh-danh-cho-nguoi-tre.jpg',
      description: 'Định hướng tư duy và kỹ năng sống cho giới trẻ.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Người trẻ',
        title: '3 ĐIỀU KIỆN THUẬN LỢI CỦA TUỔI TRẺ',
        subtitle: 'SỨC KHỎE — TRÍ TUỆ — THỜI GIAN',
        imageUrl: '/images/tong-chi/lo-trinh-danh-cho-nguoi-tre.jpg',
        description: 'Đừng lãng phí tuổi trẻ vào những tranh đua vô nghĩa; hãy dùng năng lượng tươi trẻ để phụng sự nhân sinh.',
        linkUrl: '/gioi-thieu/su-phu-tru-tri',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 18. LỘ TRÌNH CHO NGƯỜI BẬN RỘN
  {
    id: 18,
    slug: 'lo-trinh-tu-hoc-nguoi-ban-ron',
    title: 'LỘ TRÌNH TU HỌC DÀNH CHO NGƯỜI BẬN RỘN',
    subtitle: 'Nuôi dưỡng đời sống tỉnh thức ngay giữa công việc, gia đình và bộn bề thường nhật',
    category: 'lo-trinh-tu-hoc',
    categoryName: 'LỘ TRÌNH TU HỌC',
    bannerImage: '/images/tong-chi/lo-trinh-danh-cho-nguoi-moi-bat-dau.jpg',
    excerpt: 'Không cần phải vào rừng sâu mới tu được; người bận rộn hoàn toàn có thể biến từng khoảnh khắc làm việc thành pháp tu an lạc.',
    content: parsedDocs['II_4_3_LT_NGUOI_BAN_RON.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T11:30:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'TU TRONG CÔNG VIỆC — TỈNH THỨC TRONG TỪNG PHÚT GIÂY',
      subtitle: 'Phật ở ngay đây — Trong tâm con đó',
      description: 'Nghệ thuật dừng lại (Stopping) và chuyển hóa stress giữa nhịp sống công sở và gia đình.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'LỘ TRÌNH TU HỌC',
      title: 'PHẬT PHÁP TRONG TỪNG KHOẢNH KHẮC THƯỜNG NHẬT',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/lo-trinh-danh-cho-nguoi-moi-bat-dau.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'THỰC TẬP TỈNH THỨC GIỮA ĐỜI THƯỜNG',
        imageUrl: '/images/tong-chi/lo-trinh-danh-cho-nguoi-moi-bat-dau.jpg',
        khuVuc: 'Đời Sống Gia Đình',
        noiDung: 'Biết dừng lại để tìm ra chính mình và gìn giữ mái ấm hạnh phúc.',
      },
    ],
    sourceBook: {
      bookTitle: 'Thiền Ứng Dụng Cho Người Bận Rộn',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/lo-trinh-danh-cho-nguoi-moi-bat-dau.jpg',
      description: 'Phương pháp nuôi dưỡng tâm an lạc khi thời gian hạn hẹp.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Bận rộn',
        title: 'PHẬT Ở NGAY NƠI BẠN',
        subtitle: 'DỪNG LẠI VÀ TRỞ VỀ VỚI CHÍNH MÌNH',
        imageUrl: '/images/tong-chi/lo-trinh-danh-cho-nguoi-moi-bat-dau.jpg',
        description: 'Bắt đầu ngày mới bằng tâm biết ơn; làm việc hết lòng không toan tính; trở về nhà với tình thương chân thật.',
        linkUrl: '/gioi-thieu/van-hoa-ung-xu',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 19. LỘ TRÌNH CHO NGƯỜI CHUYÊN TU
  {
    id: 19,
    slug: 'lo-trinh-tu-hoc-nguoi-chuyen-tu',
    title: 'LỘ TRÌNH TU HỌC DÀNH CHO NGƯỜI CHUYÊN TU',
    subtitle: 'Kiên trì chuyển hóa tự thân, nuôi lớn tâm Bồ Đề và phụng sự bằng đời sống hành trì',
    category: 'lo-trinh-tu-hoc',
    categoryName: 'LỘ TRÌNH TU HỌC',
    bannerImage: '/images/tong-chi/lo-trinh-danh-cho-nguoi-chuyen-tu.png',
    excerpt: 'Học – Tu – Chấp tác song hành giúp hành giả chuyên tu giữ vững sơ tâm Bồ Đề, đạt được an lạc và giải thoát rốt ráo.',
    content: parsedDocs['II_4_4_LT_NGUOI_CHUYEN_TU.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T11:40:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'HÀNH TRÌ CỦA BẬC CHUYÊN TU — PHÁP HỌC VÀ PHÁP HÀNH SONG SONG',
      subtitle: 'Giữ gìn mạng mạch chánh pháp',
      description: 'Khai thị về ba việc người tu cần cân bằng: Học lấy tư lương, Tu để chuyển hóa, Chấp tác tạo phúc báu.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'LỘ TRÌNH TU HỌC',
      title: 'NGƯỜI ĐỆ TỬ THUẦN THÀNH — BẢN THỂ THANH TỊNH CỦA TAM BẢO',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/lo-trinh-danh-cho-nguoi-chuyen-tu.png',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'HÀNG HẬU HỌC TINH TẤN CHUYÊN TU',
        imageUrl: '/images/tong-chi/lo-trinh-danh-cho-nguoi-chuyen-tu.png',
        khuVuc: 'Tịnh Thất & Giảng Đường Hòa Phúc',
        noiDung: 'Đời sống thanh bần, sớm khuya kệ kinh gìn giữ nếp thiền môn.',
      },
    ],
    sourceBook: {
      bookTitle: 'Cẩm Nang Người Xuất Gia & Chuyên Tu',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/lo-trinh-danh-cho-nguoi-chuyen-tu.png',
      description: 'Định hướng lộ trình tu học chuyên sâu.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Chuyên tu',
        title: 'BA TRỤ CỘT HÀNH TRÌ CHUYÊN SÂU',
        subtitle: 'HỌC (TƯ LƯƠNG) — TU (CHUYỂN HÓA) — CHẤP TÁC (PHÚC BÁU)',
        imageUrl: '/images/tong-chi/lo-trinh-danh-cho-nguoi-chuyen-tu.png',
        description: 'Giữ chánh kiến, kiên định trên con đường giải thoát và làm gương sáng cho đời.',
        linkUrl: '/gioi-thieu/su-phu-tru-tri',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 20. VĂN HÓA ỨNG XỬ
  {
    id: 20,
    slug: 'van-hoa-ung-xu-giao-tiep-tai-chua',
    title: 'VĂN HÓA GIAO TIẾP & ỨNG XỬ TẠI CHÙA',
    subtitle: 'Nếp sống hòa hợp, kính trên nhường dưới và giữ gìn thanh quy chốn thiền môn',
    category: 'nep-song-thien-gia',
    categoryName: 'NẾP SỐNG THIỀN GIA',
    bannerImage: '/images/tong-chi/van-hoa-ung-xu-giao-tiep-tai-chua.jpg',
    excerpt: 'Văn hóa ứng xử tại chốn Tùng Lâm thể hiện phẩm hạnh và sự tỉnh thức của người đệ tử Phật qua từng lời nói, nụ cười và hành động.',
    content: parsedDocs['II_5_1_VAN_HOA_UNG_XU.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T11:50:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'VĂN HÓA ỨNG XỬ TẠI TÙNG LÂM HÒA PHÚC',
      subtitle: 'Văn là cái đẹp — Hóa là chuyển hóa và lan tỏa',
      description: 'Quy định sinh hoạt và văn hóa giao tiếp tại Nhà Khách, Trai Đường, Nhà Bếp, Chánh Điện.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'NẾP SỐNG THIỀN GIA',
      title: 'VĂN HÓA THIỀN MÔN — NỀN TẢNG KIẾN TẠO MÔI TRƯỜNG TU HỌC THANH TỊNH',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/van-hoa-ung-xu-giao-tiep-tai-chua.jpg',
      linkUrl: '/gioi-thieu/van-hoa-ung-xu',
    },
    photoGallery: [
      {
        title: 'VĂN HÓA CHẮP TAY XÁ CHÀO TRANG NGHIÊM',
        imageUrl: '/images/tong-chi/van-hoa-ung-xu-giao-tiep-tai-chua.jpg',
        khuVuc: 'Khu Nhà Khách Hòa Phúc',
        noiDung: 'Nụ cười từ hòa và lời chào A Di Đà Phật làm ấm lòng khách thập phương.',
      },
    ],
    sourceBook: {
      bookTitle: 'Nếp Sống Văn Hóa Tùng Lâm Hòa Phúc',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/van-hoa-ung-xu-giao-tiep-tai-chua.jpg',
      description: 'Nội quy và thanh quy chốn già lam.',
      linkUrl: '/gioi-thieu/van-hoa-ung-xu',
    },
    keywords: [
      {
        keyword: 'Văn hóa ứng xử',
        title: 'VĂN HÓA GIAO TIẾP THIỀN MÔN',
        subtitle: 'LẮNG NGHE — CHUYỂN HÓA — LAN TỎA ĐIỀU THIỆN',
        imageUrl: '/images/tong-chi/van-hoa-ung-xu-giao-tiep-tai-chua.jpg',
        description: 'Đi nhẹ, nói khẽ, mỉm cười, giữ gìn oai nghi và kính trọng chư Tăng Ni cùng đạo hữu.',
        linkUrl: '/gioi-thieu/van-hoa-ung-xu',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 21. OAI NGHI NGƯỜI CON PHẬT
  {
    id: 21,
    slug: 'oai-nghi-nguoi-con-phat',
    title: 'OAI NGHI NGƯỜI CON PHẬT',
    subtitle: 'Giữ gìn thân hành đoan chính, nuôi dưỡng sự tỉnh thức trong từng bước đi đứng nằm ngồi',
    category: 'nep-song-thien-gia',
    categoryName: 'NẾP SỐNG THIỀN GIA',
    bannerImage: '/images/tong-chi/oai-nghi-nguoi-con-phat.jpg',
    excerpt: 'Tác phong đĩnh đạc, trang phục tề chỉnh, nói năng từ hòa là biểu hiện của một nội tâm có tu tập và có sự tự chủ.',
    content: parsedDocs['II_5_2_OAI_NGHI_NGUOI_CON_PHAT.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T12:00:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'BỐN OAI NGHI ĐI ĐỨNG NẰM NGỒI',
      subtitle: 'Hành như phong, Tọa như chung, Lập như tùng, Ngọa như cung',
      description: 'Chỉ dẫn oai nghi của người con Phật khi đến chùa và trong sinh hoạt đời thường.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'NẾP SỐNG THIỀN GIA',
      title: 'OAI NGHI THIỀN MÔN — TẤM GƯƠNG PHẢN CHIẾU TÂM HỒN',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/oai-nghi-nguoi-con-phat.jpg',
      linkUrl: '/gioi-thieu/van-hoa-ung-xu',
    },
    photoGallery: [
      {
        title: 'OAI NGHI KHI ĐẾN CHÙA',
        imageUrl: '/images/tong-chi/oai-nghi-nguoi-con-phat.jpg',
        khuVuc: 'Chánh Điện & Khuôn Viên',
        noiDung: 'Áo tràng lam trang nhã, bước đi nhẹ nhàng thanh thoát.',
      },
    ],
    sourceBook: {
      bookTitle: 'Oai Nghi Người Phật Tử',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/oai-nghi-nguoi-con-phat.jpg',
      description: 'Sách rèn luyện tác phong người học Phật.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Oai nghi',
        title: 'OAI NGHI ĐOAN CHÍNH',
        subtitle: 'ĐỨC CAO, HỶ XẢ, KHINH AN — ĐOAN THÂN, CHÍNH NIỆM CHẲNG MÀNG THỊ PHI',
        imageUrl: '/images/tong-chi/oai-nghi-nguoi-con-phat.jpg',
        description: 'Tác phong đĩnh đạc, từ hòa, kham nhẫn lắng nghe, quần áo gọn gàng sạch sẽ.',
        linkUrl: '/gioi-thieu/van-hoa-ung-xu',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 22. BỔN PHẬN NGƯỜI PHẬT TỬ TẠI GIA
  {
    id: 22,
    slug: 'bon-phan-nguoi-phat-tu-tai-gia',
    title: 'BỔN PHẬN NGƯỜI PHẬT TỬ TẠI GIA',
    subtitle: 'Sống tốt đời đẹp đạo, làm tròn trách nhiệm đối với gia đình, xã hội và Tam Bảo',
    category: 'nep-song-thien-gia',
    categoryName: 'NẾP SỐNG THIỀN GIA',
    bannerImage: '/images/tong-chi/bon-phan-nguoi-phat-tu-tai-gia.jpg',
    excerpt: 'Người Phật tử tại gia là nhịp cầu gắn kết đạo pháp với cuộc đời, đem tinh thần từ bi và trí tuệ làm rạng rỡ gia phong và xã hội.',
    content: parsedDocs['II_5_3_BON_PHAN_PT_TAI_GIA.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T12:10:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'LÀM TRÒN BỔN PHẬN ĐỂ TỐT ĐỜI ĐẸP ĐẠO',
      subtitle: 'Hiếu dưỡng cha mẹ, hòa thuận gia đình, hộ trì Tam Bảo',
      description: 'Giảng giải về bổn phận trong gia đình huyết thống và gia đình tâm linh theo lời Phật dạy trong Kinh Thiện Sanh.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'NẾP SỐNG THIỀN GIA',
      title: 'BỔN PHẬN PHẬT TỬ TẠI GIA THEO TINH THẦN KINH THIỆN SANH',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/bon-phan-nguoi-phat-tu-tai-gia.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'GIA ĐÌNH PHẬT TỬ HÒA PHÚC',
        imageUrl: '/images/tong-chi/bon-phan-nguoi-phat-tu-tai-gia.jpg',
        khuVuc: 'Giảng Đường Hòa Phúc',
        noiDung: 'Các thế hệ ông bà, cha mẹ, con cháu cùng nhau câu hội tu học.',
      },
    ],
    sourceBook: {
      bookTitle: 'Bổn Phận Người Phật Tử Tại Gia',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/bon-phan-nguoi-phat-tu-tai-gia.jpg',
      description: 'Sách hướng dẫn đạo làm con, làm cha mẹ và công dân mẫu mực.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Bổn phận',
        title: 'BỐN CHÚNG ĐỆ TỬ PHẬT',
        subtitle: 'XUẤT GIA (TỲ-KHEO, TỲ-KHEO-NI) & TẠI GIA (ƯU-BÀ-TẮC, ƯU-BÀ-DI)',
        imageUrl: '/images/tong-chi/bon-phan-nguoi-phat-tu-tai-gia.jpg',
        description: 'Ứng dụng lời Phật dạy vào công việc, gia đình, làm tròn bổn phận để lợi mình lợi người.',
        linkUrl: '/gioi-thieu/su-phu-tru-tri',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 23. ĂN CHAY
  {
    id: 23,
    slug: 'an-chay-tinh-hoa-than-tam',
    title: 'ĂN CHAY — TỊNH HÓA THÂN TÂM & NUÔI LÒNG TỪ',
    subtitle: 'Tôn trọng sự sống, nuôi dưỡng lòng từ bi và giữ gìn hạnh phúc gia đình',
    category: 'nep-song-thien-gia',
    categoryName: 'NẾP SỐNG THIỀN GIA',
    bannerImage: '/images/tong-chi/tong-chi-tu-hoc-banner.jpg',
    excerpt: 'Ăn chay là cách thiết thực nhất để dừng nghiệp sát sinh, bồi dưỡng lòng trắc ẩn và bảo vệ sức khỏe thân tâm an lành.',
    content: parsedDocs['II_5_4_AN_CHAY.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T12:20:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'LỜI SƯ PHỤ DẠY VỀ NGHỆ THUẬT ĂN CHAY',
      subtitle: 'Ăn chay nuôi lòng từ — Chớ vì ăn mất hạnh phúc gia đình',
      description: 'Khuyên nhủ về cách ăn chay tùy duyên, khéo léo đảm bảo dinh dưỡng và hòa hợp với gia đình người thân.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'NẾP SỐNG THIỀN GIA',
      title: 'ĂN CHAY VÀ GIÁ TRỊ CỐT LÕI CỦA SỰ SỐNG',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/tong-chi-tu-hoc-banner.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'BỮA CƠM CHAY THANH TỊNH TÙNG LÂM',
        imageUrl: '/images/tong-chi/tong-chi-tu-hoc-banner.jpg',
        khuVuc: 'Trai Đường Hòa Phúc',
        noiDung: 'Món chay giản dị đượm đà hương vị giải thoát và lòng biết ơn.',
      },
    ],
    sourceBook: {
      bookTitle: 'Nghệ Thuật Ăn Chay & Sống Xanh',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/tong-chi-tu-hoc-banner.jpg',
      description: 'Chỉ dẫn ăn chay lành mạnh và nuôi dưỡng tâm từ.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Ăn chay',
        title: 'ĂN CHAY VÌ SỰ SỐNG',
        subtitle: 'NUÔI LÒNG BI MẪN — KHÔNG LÀM TỔN HẠI CHÚNG SINH',
        imageUrl: '/images/tong-chi/tong-chi-tu-hoc-banner.jpg',
        description: 'Ăn chay vì sức khỏe, vì môi trường và vì tình thương bình đẳng đối với muôn loài.',
        linkUrl: '/gioi-thieu/van-hoa-ung-xu',
      },
    ],
    updatedAt: new Date().toISOString(),
  },

  // 24. PHÓNG SINH & BẢO VỆ MÔI TRƯỜNG
  {
    id: 24,
    slug: 'phong-sinh-tu-phuc-bao-ve-moi-truong',
    title: 'PHÓNG SINH TU PHÚC & BẢO VỆ MÔI TRƯỜNG',
    subtitle: 'Mở rộng lòng từ, tôn trọng sự sống và hành động có trí tuệ',
    category: 'nep-song-thien-gia',
    categoryName: 'NẾP SỐNG THIỀN GIA',
    bannerImage: '/images/tong-chi/phong-sinh-tu-phuc.jpg',
    excerpt: 'Phóng sinh đúng chánh pháp phải gắn liền với sự thấu hiểu, bảo vệ môi trường sinh thái để muôn loài thật sự được tự do và an lành.',
    content: parsedDocs['II_5_5_PHONG_SINH_BV_MOI_TRUONG.docx'] || '',
    author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
    authorLink: '/gioi-thieu/su-phu-tru-tri',
    publishedAt: '2026-08-23T12:30:00.000Z',
    status: 'published',
    videoBlock: {
      title: 'PHÓNG SINH ĐÚNG CHÁNH PHÁP TẠI TÙNG LÂM HÒA PHÚC',
      subtitle: 'Sự sống được thấu hiểu ➔ Được tôn trọng ➔ Được an lành',
      description: 'Hướng dẫn phóng sinh văn minh, chọn môi trường phù hợp và không tiếp tay cho nạn săn bắt bẫy hại.',
      videoUrl: 'https://www.youtube.com/watch?v=MKt_sLwxmNU',
    },
    featuredArticle: {
      label: 'NẾP SỐNG THIỀN GIA',
      title: 'PHÓNG SINH CÓ TRÍ TUỆ VÀ Ý THỨC BẢO VỆ MÔI TRƯỜNG SINH THÁI',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      bgImage: '/images/tong-chi/phong-sinh-tu-phuc.jpg',
      linkUrl: '/tri-tue-phat-phap',
    },
    photoGallery: [
      {
        title: 'HOẠT ĐỘNG PHÓNG SINH VĂN MINH',
        imageUrl: '/images/tong-chi/phong-sinh-tu-phuc.jpg',
        khuVuc: 'Khu Bảo Tồn & Sông Hồ Tự Nhiên',
        noiDung: 'Thả các loài thủy tộc về với môi trường tự nhiên trong lời nguyện cầu an lành.',
      },
    ],
    sourceBook: {
      bookTitle: 'Phóng Sinh & Tôn Trọng Sự Sống',
      author: 'Sa Môn Vô Trí (Thích Tâm Hòa)',
      coverImage: '/images/tong-chi/phong-sinh-tu-phuc.jpg',
      description: 'Chỉ dẫn phóng sinh văn minh và trách nhiệm môi trường.',
      linkUrl: '/tri-tue-phat-phap',
    },
    keywords: [
      {
        keyword: 'Phóng sinh',
        title: 'PHÓNG SINH VĂN MINH & CÓ TRÍ TUỆ',
        subtitle: 'ĐỂ TỰ DO CÓ MẶT — ĐỂ SỰ SỐNG ĐƯỢC TỒN TẠI',
        imageUrl: '/images/tong-chi/phong-sinh-tu-phuc.jpg',
        description: 'Phóng sinh phải xuất phát từ tâm từ bi và trí tuệ, tránh các hình thức phóng sinh hình thức gây hại cho động vật.',
        linkUrl: '/gioi-thieu/van-hoa-ung-xu',
      },
    ],
    updatedAt: new Date().toISOString(),
  },
];

// Write back to tong-chi-data.json
fs.writeFileSync(
  'C:\\Users\\MY PC\\Tung_Lam_Hoa_Phuc_Web\\src\\data\\tong-chi-data.json',
  JSON.stringify(fullArticles, null, 2),
  'utf8'
);

console.log(`Successfully generated and saved ${fullArticles.length} articles to src/data/tong-chi-data.json!`);
