import fs from 'fs';
import path from 'path';

const targetDir = 'E:\\PHAP_THOAI_PHAT_TU_CHON_LOC';

if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

// 1. TÀI LIỆU HƯỚNG DẪN & COPY CHO PHẬT TỬ
const guideLines = [
  "================================================================================",
  "🛕 TÙNG LÂM HÒA PHÚC — BỘ PHÁP THOẠI TUYỂN CHỌN CHO QUÝ PHẬT TỬ 🛕",
  "================================================================================",
  "(Tài liệu nội bộ phục vụ việc sao chép thẻ nhớ/USB & chia sẻ Phật pháp)",
  "",
  "Kính bạch Quý Thầy, kính thưa Quý Phật tử và Ban Hoằng Pháp,",
  "",
  "Thư mục này được biên tập và chọn lọc kỹ lưỡng từ kho dữ liệu âm thanh của Chùa,",
  "đã qua khâu lọc tạp âm, chuẩn hóa âm lượng (Master Audio 44.1kHz), đặt tên có",
  "đánh số thứ tự (01, 02, 03...) để quý vị dễ dàng chép vào loa Pháp thoại, USB,",
  "hoặc điện thoại mà không bị nhảy lộn xộn thứ tự bài giảng.",
  "",
  "--------------------------------------------------------------------------------",
  "I. DANH MỤC CÁC BỘ PHÁP THOẠI TRONG THƯ MỤC NÀY",
  "--------------------------------------------------------------------------------",
  "",
  "📂 01. SERIES - TÔN GIẢ ĐẠI MỤC KIỀN LIÊN (09 TẬP)",
  "Giảng sư: Đại đức Thích Tâm Hòa",
  "Chủ đề cốt tủy: Bát Nhã – Duyên Khởi – Hạnh Nguyện – Chuyển Hóa Nhận Thức",
  "• Tập 01: Hạnh Nguyện Ban Sơ (75 phút) — Điều gì giữ người tu không bỏ cuộc?",
  "• Tập 02: Ưu Tư Thời Niên Thiếu (82 phút) — 3 bước chuyển hóa vọng tưởng.",
  "• Tập 03: Khơi Nguồn Hạnh Nguyện (56 phút) — Sống tỉnh thức, hướng thượng.",
  "• Tập 04: Giữ Vững Chí Nguyện (65 phút) — Nắng gió tôi luyện nên cây lớn.",
  "• Tập 05: Tự Do Đích Thực (70 phút) — Làm chủ thân tâm, phá vỡ ngã chấp.",
  "• Tập 06: Mục Đích Tối Hậu (85 phút) — Chấm dứt sinh tử khổ đau.",
  "• Tập 07: Giữ Chất Người Tu (62 phút) — Học hạnh của nước mềm mại, bền bỉ.",
  "• Tập 08: Cánh Cửa Bất Tử (78 phút) — Ai thấy duyên khởi là thấy Như Lai.",
  "• Tập 09: Đạo Lộ Giải Thoát (66 phút) — Phật pháp không có con đường tắt.",
  "",
  "📂 02. SERIES - KINH TẠP A HÀM - HIẾU DƯỠNG CHA MẸ (03 TẬP)",
  "Giảng sư: Đại đức Thích Tâm Hòa",
  "Chủ đề cốt tủy: Đạo Hiếu Phật Giáo & Kiến Tạo Mái Ấm Gia Đình An Vui",
  "• Tập 01: Lời Phật Dạy Về Hiếu Dưỡng Cha Mẹ (68 phút) — Nền tảng tâm hiếu.",
  "• Tập 02: Hạnh Phúc Gia Đình (62 phút) — Chuyển hóa bất đồng thế hệ.",
  "• Tập 03: Báo Đáp Thâm Ân (70 phút) — Dẫn dắt cha mẹ hướng về chánh đạo.",
  "",
  "📂 03. SERIES - PHÁP ÂM CHUYỂN HÓA & BÌNH AN NỘI TÂM (04 TẬP)",
  "Giảng sư: Sa-môn Vô Trí",
  "Chủ đề cốt tủy: Tâm lý chữa lành & Chánh niệm ứng dụng",
  "• Bài 01: Làm Thế Nào Để Gia Đình Hạnh Phúc (58 phút)",
  "• Bài 02: Làm Cách Nào Để Duy Trì Sự Bình An (54 phút)",
  "• Bài 03: Đâu Là Con Đường Đi Đến Hạnh Phúc (60 phút)",
  "• Bài 04: Làm Việc Hiệu Quả Trong Chánh Niệm (52 phút)",
  "",
  "📂 04. SERIES - BỒ ĐỀ TÂM HÀNH TRÌ NGHI QUỸ",
  "Giảng sư: Đại đức Thích Tâm Hòa",
  "• Bài 01: Điều Gì Giúp Người Con Phật Luôn Vững Vàng (45 phút)",
  "Mật hạnh âm thầm: Bồ Tát đạo từ những việc nhỏ bé thường nhật.",
  "",
  "📂 05. SERIES - KHAI THỊ & CẢNH SÁCH NGÀY TRAI",
  "• Bài 01: Lá Thư Khai Thị Trước Thềm Năm Bính Ngọ (25 phút)",
  "• Bài 02: Lá Thư Mùa Trung Thu (15 phút)",
  "• Bài 03: Cảnh Sách Diễn Nôm Sáng Chiều (ĐĐ. Minh Hạnh) (18 phút)",
  "• Bài 04: Cảnh Sách Ngày Trai Buổi Chiều (15 phút)",
  "• Bài 05: Cảnh Sách Ngày Trai Buổi Sáng (15 phút)",
  "",
  "--------------------------------------------------------------------------------",
  "II. MẪU TIN NHẮN GỬI KÈM KHI CHIA SẺ PHÁP THOẠI CHO PHẬT TỬ",
  "--------------------------------------------------------------------------------",
  "Quý Phật tử có thể sao chép đoạn văn dưới đây để gửi qua Zalo/Facebook:",
  "",
  "\"Nam Mô Bổn Sư Thích Ca Mâu Ni Phật!",
  "Kính gửi Quý Đạo hữu và gia đình,",
  "Ban Văn Thư Tùng Lâm Hòa Phúc xin tùy hỷ gửi tặng Quý vị tuyển tập Pháp thoại",
  "chọn lọc của Thầy Viện Chủ Thích Tâm Hòa và chư Tăng. Những lời khai thị mộc mạc,",
  "sâu sắc sẽ giúp nuôi dưỡng tâm an lạc, tháo gỡ những khúc mắc trong đời sống",
  "và gia đình, đồng thời bồi đắp hạnh nguyện giải thoát.",
  "Kính chúc Quý vị và gia quyến luôn thân tâm an lạc, vạn sự cát tường,",
  "tinh tấn trên con đường tu học chánh pháp!",
  "A Di Đà Phật.\"",
  "",
  "--------------------------------------------------------------------------------",
  "III. HƯỚNG DẪN CHÉP VÀO USB / THẺ NHỚ LOA PHÁP",
  "--------------------------------------------------------------------------------",
  "1. Cắm USB hoặc Thẻ nhớ MicroSD vào máy tính.",
  "2. Kiểm tra định dạng thẻ nhớ nên là FAT32 hoặc exFAT để loa dễ nhận diện.",
  "3. Chọn các thư mục cần chép từ thư mục này, bấm Chuột phải -> Copy,",
  "   sau đó Paste trực tiếp vào thẻ nhớ.",
  "4. Tên các file đã được đánh số thứ tự 01, 02, 03..., loa sẽ phát theo đúng",
  "   trình tự từng bài rất mạch lạc."
];

fs.writeFileSync(path.join(targetDir, '00_HUONG_DAN_GUI_PHAP_THOAI_CHO_PHAT_TU.txt'), guideLines.join('\r\n'), 'utf8');

// 2. CẨM NANG ĐĂNG YOUTUBE
const youtubeLines = [
  "================================================================================",
  "🛕 TÙNG LÂM HÒA PHÚC — CẨM NANG ĐĂNG TẢI YOUTUBE THEO TỪNG SERIES 🛕",
  "================================================================================",
  "",
  "--------------------------------------------------------------------------------",
  "SERIES 1: TÔN GIẢ ĐẠI MỤC KIỀN LIÊN (09 TẬP)",
  "Playlist đề xuất: \"Đại Đệ Tử Phật - Tôn Giả Mục Kiền Liên | ĐĐ. Thích Tâm Hòa\"",
  "Danh mục (Category): Giáo dục / Phi lợi nhuận",
  "--------------------------------------------------------------------------------",
  "",
  "[TẬP 1]",
  "• TIÊU ĐỀ YOUTUBE:",
  "Hạnh Nguyện Ban Sơ — Series Tôn Giả Mục Kiền Liên (Tập 1) | ĐĐ. Thích Tâm Hòa",
  "• MÔ TẢ (DESCRIPTION):",
  "🙏 ĐẠI MỤC KIỀN LIÊN – TẬP 1: HẠNH NGUYỆN BAN SƠ 🙏",
  "Điều gì giữ một người không bỏ cuộc trên con đường tu học?",
  "Đó có thể là nhân duyên, là pháp lữ đồng hành, nhưng sâu xa hơn chính là hạnh nguyện ban sơ của mỗi người.",
  "Trong buổi chia sẻ đầu tiên thuộc series về Tôn giả Đại Mục Kiền Liên tại Tùng Lâm Hòa Phúc, Đại đức Thích Tâm Hòa nhấn mạnh tinh thần cầu học chân chính, sự khiêm hạ và giá trị của việc hiểu đúng nhân duyên để giữ vững chí nguyện tu tập.",
  "✨ Học Phật không phải để biết nhiều hơn, mà để sống sâu sắc và tỉnh thức hơn mỗi ngày.",
  "",
  "⏱ MỤC LỤC THỜI GIAN (TIMESTAMPS):",
  "00:00 - Lời mở đầu & Tinh thần trạch pháp cầu học",
  "15:30 - Đến với đạo vì hạnh nguyện ban sơ",
  "35:20 - Hiểu nhân duyên để giữ vững hạnh nguyện",
  "52:10 - Tình pháp lữ – Sự đồng hành thiêng liêng",
  "01:10:00 - Không có đạo, mình sẽ là ai?",
  "01:14:20 - Hồi hướng công đức",
  "",
  "🏷 HASHTAGS:",
  "#DaiMucKienLien #HanhNguyenBanSo #ThichTamHoa #TungLamHoaPhuc #PhatPhapUngDung #TuHocPhatPhap",
  "",
  "---",
  "",
  "[TẬP 2]",
  "• TIÊU ĐỀ YOUTUBE:",
  "Ưu Tư Thời Niên Thiếu — Series Tôn Giả Mục Kiền Liên (Tập 2) | ĐĐ. Thích Tâm Hòa",
  "• MÔ TẢ:",
  "🙏 ĐẠI MỤC KIỀN LIÊN – TẬP 2: ƯU TƯ THỜI NIÊN THIẾU 🙏",
  "Không phải mọi ưu tư của tuổi trẻ đều là yếu đuối. Có những thao thức chính là khởi điểm cho một đời sống lớn hơn, sâu sắc hơn và cao thượng hơn.",
  "Đại đức Thích Tâm Hòa chia sẻ về những ưu tư đã đánh thức chí nguyện xuất ly, sức mạnh của tịnh tín, và 3 bước vàng chuyển hóa vọng tưởng.",
  "⏱ MỤC LỤC THỜI GIAN:",
  "00:00 - Tịnh tín hôm nay – Phước báu mai sau",
  "25:23 - Cùng chung chí nguyện & Cốt cách thánh giả",
  "56:51 - Những ưu tư thời niên thiếu đánh thức chí nguyện xuất ly",
  "01:15:00 - 3 bước vàng chuyển hóa vọng tưởng",
  "01:21:00 - Hồi hướng",
  "🏷 HASHTAGS:",
  "#DaiMucKienLien #UuTuThoiNienThieu #ThichTamHoa #XuatLy #TuHocPhatPhap #ChuyenHoaVongTuong",
  "",
  "---",
  "",
  "[TẬP 3]",
  "• TIÊU ĐỀ YOUTUBE:",
  "Khơi Nguồn Hạnh Nguyện — Series Tôn Giả Mục Kiền Liên (Tập 3) | ĐĐ. Thích Tâm Hòa",
  "• MÔ TẢ:",
  "🙏 ĐẠI MỤC KIỀN LIÊN – TẬP 3: KHƠI NGUỒN HẠNH NGUYỆN 🙏",
  "Một đời sống cao thượng không bắt đầu từ sự hưởng thụ, mà bắt đầu từ một hạnh nguyện đủ lớn để vượt lên những ràng buộc của thế tục.",
  "Khi tâm Bồ Đề được khơi mở, con người sống tỉnh thức, biết đủ và hướng đời mình đến những giá trị bền vững.",
  "🏷 HASHTAGS: #DaiMucKienLien #KhoiNguonHanhNguyen #TamBoDe #ThichTamHoa #TungLamHoaPhuc",
  "",
  "---",
  "",
  "[TẬP 4]",
  "• TIÊU ĐỀ YOUTUBE:",
  "Giữ Vững Chí Nguyện — Series Tôn Giả Mục Kiền Liên (Tập 4) | ĐĐ. Thích Tâm Hòa",
  "• MÔ TẢ:",
  "🙏 ĐẠI MỤC KIỀN LIÊN – TẬP 4: GIỮ VỮNG CHÍ NGUYỆN 🙏",
  "Chí nguyện không lớn lên trong sự thuận lợi, mà được tôi luyện qua nghịch cảnh. Nắng gió không làm cây gục ngã nếu rễ cây còn bám sâu vào lòng đất.",
  "🏷 HASHTAGS: #DaiMucKienLien #GiuVungChiNguyen #NoiLuc #ThichTamHoa #ChanhKien",
  "",
  "---",
  "",
  "[TẬP 5]",
  "• TIÊU ĐỀ YOUTUBE:",
  "Tự Do Đích Thực — Series Tôn Giả Mục Kiền Liên (Tập 5) | ĐĐ. Thích Tâm Hòa",
  "• MÔ TẢ:",
  "🙏 ĐẠI MỤC KIỀN LIÊN – TẬP 5: TỰ DO ĐÍCH THỰC 🙏",
  "Tự do không phải là làm theo điều mình muốn, mà là khả năng thấy rõ bản ngã để quay về làm chủ thân tâm bằng trí tuệ và giới luật.",
  "🏷 HASHTAGS: #DaiMucKienLien #TuDoDichThuc #LamChuChinhMinh #ThichTamHoa #TinhTan",
  "",
  "---",
  "",
  "[TẬP 6]",
  "• TIÊU ĐỀ YOUTUBE:",
  "Mục Đích Tối Hậu — Series Tôn Giả Mục Kiền Liên (Tập 6) | ĐĐ. Thích Tâm Hòa",
  "• MÔ TẢ:",
  "🙏 ĐẠI MỤC KIỀN LIÊN – TẬP 6: MỤC ĐÍCH TỐI HẬU 🙏",
  "Chén cao thì nước không vào, tâm cao thì đạo không đến. Nhìn lại mục đích tối hậu của việc tu học: chấm dứt khổ đau và sinh tử luân hồi.",
  "🏷 HASHTAGS: #DaiMucKienLien #MucDichToiHau #KhiemHa #GiaiThoat #ThichTamHoa",
  "",
  "---",
  "",
  "[TẬP 7]",
  "• TIÊU ĐỀ YOUTUBE:",
  "Giữ Chất Người Tu — Series Tôn Giả Mục Kiền Liên (Tập 7) | ĐĐ. Thích Tâm Hòa",
  "• MÔ TẢ:",
  "🙏 ĐẠI MỤC KIỀN LIÊN – TẬP 7: GIỮ CHẤT NGƯỜI TU 🙏",
  "Còn phụng sự là còn hạnh phúc. Học theo hạnh của nước: mềm mại nhưng bền bỉ, kiên cường giữ gìn tâm ban đầu giữa thế gian nhiều biến động.",
  "🏷 HASHTAGS: #DaiMucKienLien #GiuChatNguoiTu #TamBoDe #PhungSu #HanhCuaNuoc",
  "",
  "---",
  "",
  "[TẬP 8]",
  "• TIÊU ĐỀ YOUTUBE:",
  "Cánh Cửa Bất Tử — Series Tôn Giả Mục Kiền Liên (Tập 8) | ĐĐ. Thích Tâm Hòa",
  "• MÔ TẢ:",
  "🙏 ĐẠI MỤC KIỀN LIÊN – TẬP 8: CÁNH CỬA BẤT TỬ 🙏",
  "Ai thấy duyên khởi là thấy Như Lai. Vượt thoát những tìm cầu hữu hạn để bước vào con đường giải thoát bất tử.",
  "🏷 HASHTAGS: #DaiMucKienLien #CanhCuaBatTu #DuyenKhoi #ThichTamHoa #TungLamHoaPhuc",
  "",
  "---",
  "",
  "[TẬP 9]",
  "• TIÊU ĐỀ YOUTUBE:",
  "Đạo Lộ Giải Thoát — Series Tôn Giả Mục Kiền Liên (Tập 9) | ĐĐ. Thích Tâm Hòa",
  "• MÔ TẢ:",
  "🙏 ĐẠI MỤC KIỀN LIÊN – TẬP 9: ĐẠO LỘ GIẢI THOÁT 🙏",
  "Phật pháp không có con đường tắt. Nuôi dưỡng và bảo lưu hạt giống Bồ Đề qua từng nhân duyên cuộc đời.",
  "🏷 HASHTAGS: #DaiMucKienLien #DaoLoGiaiThoat #BoDeTam #ThichTamHoa #HoanManSeries",
  "",
  "================================================================================",
  "SERIES 2: LỜI PHẬT DẠY VỀ HIẾU DƯỠNG CHA MẸ (KINH TẠP A HÀM)",
  "Playlist đề xuất: \"Kinh Tạp A Hàm - Lời Phật Dạy Về Hiếu Dưỡng Cha Mẹ | ĐĐ. Thích Tâm Hòa\"",
  "--------------------------------------------------------------------------------",
  "[TẬP 1] Nền Tảng Đạo Hiếu — Hiểu đúng lời Phật dạy về báo ân cha mẹ.",
  "[TẬP 2] Hạnh Phúc Gia Đình — Chuyển hóa bất đồng, xây dựng mái ấm an vui.",
  "[TẬP 3] Báo Đáp Thâm Ân — Hướng cha mẹ quy y Tam Bảo và tu tập chánh pháp."
];

fs.writeFileSync(path.join(targetDir, '00_CAM_NANG_DANG_YOUTUBE_PODCAST.txt'), youtubeLines.join('\r\n'), 'utf8');

console.log('✅ Đã tạo thành công cả 2 tài liệu cẩm nang tại ' + targetDir);
