import fs from 'fs';
import path from 'path';

const postcastRoot = 'E:\\VIDEO AND SOUND\\POSTCAST';
const phatTuRoot = 'E:\\PHAP_THOAI_PHAT_TU_CHON_LOC';

// 1. CẬP NHẬT 00_DANH_MUC_VA_QUY_HOACH_POSTCAST.txt
const overviewLines = [
  "================================================================================",
  "🛕 TÙNG LÂM HÒA PHÚC — QUY HOẠCH DỮ LIỆU & BỔ SUNG PHÁP THOẠI POSTCAST 🛕",
  "================================================================================",
  "Thư mục: E:\\VIDEO AND SOUND\\POSTCAST\\",
  "",
  "Kính thưa Ban Văn Thư & Ban Hoằng Pháp,",
  "",
  "Thư mục POSTCAST đã được quy hoạch mạch lạc, chuẩn hóa theo Series và tách bạch rõ ràng:",
  "• Toàn bộ các bài Pháp thoại của Sư Phụ (ĐĐ. Thích Tâm Hòa / Sa-môn Vô Trí) được đặt riêng.",
  "• Các bài tụng đọc, diễn Nôm của Chư Tăng (ĐĐ. Minh Hạnh) được chuyển sang phân khu riêng biệt.",
  "",
  "🌟 TRUNG TÂM PHÁP THOẠI HOÀN CHỈNH:",
  "👉 E:\\VIDEO AND SOUND\\POSTCAST\\00_TONG_HOP_SERIES_PHAP_THOAI_HOAN_CHINH\\",
  "",
  "--------------------------------------------------------------------------------",
  "DANH MỤC CÁC PHÂN KHU PHÁP THOẠI VÀ CHƯ TĂNG:",
  "--------------------------------------------------------------------------------",
  "",
  "A. CÁC SERIES PHÁP THOẠI CỦA SƯ PHỤ (ĐĐ. THÍCH TÂM HÒA):",
  "",
  "📂 01_SERIES_DAI_MUC_KIEN_LIEN (09 TẬP)",
  "   • Tập 01: Hạnh Nguyện Ban Sơ",
  "   • Tập 02: Ưu Tư Thời Niên Thiếu",
  "   • Tập 03: Khơi Nguồn Hạnh Nguyện",
  "   • Tập 04: Giữ Vững Chí Nguyện",
  "   • Tập 05: Tự Do Đích Thực",
  "   • Tập 06: Mục Đích Tối Hậu",
  "   • Tập 07: Giữ Chất Người Tu",
  "   • Tập 08: Cánh Cửa Bất Tử",
  "   • Tập 09: Đạo Lộ Giải Thoát",
  "   • Kèm tài liệu Marker & Timestamps 9 buổi phục vụ làm video và đăng YouTube.",
  "",
  "📂 02_SERIES_HIEU_DUONG_CHA_ME_KINH_A_HAM (03 TẬP)",
  "   • Phần 01: Lời Phật Dạy Về Hiếu Dưỡng Cha Mẹ",
  "   • Phần 02: Hạnh Phúc Gia Đình",
  "   • Phần 03: Báo Đáp Thâm Ân",
  "",
  "📂 03_SERIES_PHAP_AM_CHUYEN_HOA_TAM_LY (SA-MÔN VÔ TRÍ)",
  "   • Bài 01: Làm Thế Nào Để Gia Đình Hạnh Phúc",
  "   • Bài 02: Làm Cách Nào Để Duy Trì Sự Bình An",
  "   • Bài 03: Đâu Là Con Đường Đi Đến Hạnh Phúc",
  "   • Bài 04: Làm Việc Hiệu Quả Trong Chánh Niệm",
  "",
  "📂 04_SERIES_BO_DE_TAM_HANH_TRI_NGHI_QUY",
  "   • Bài 01: Điều Gì Giúp Người Con Phật Luôn Vững Vàng",
  "   • Kèm file tài liệu Word bài giảng chi tiết Buổi 1, Buổi 2, Buổi 3.",
  "",
  "📂 05_SERIES_CONG_TU_MOT_NGAY_AN_LAC",
  "   • Bài 01: Một Góc Nhìn Về Thực Dưỡng Oshawa Dưới Ánh Sáng Phật Pháp (ĐĐ. Thích Tâm Hòa)",
  "   • Bài 02: Tóm Tắt Chương Trước - Một Ngày An Lạc",
  "   • Bài 03: Cộng Tu Một Ngày An Lạc Tháng 07",
  "   • Bài 04: Giới Luật - Nền Tảng Của Người Tu",
  "",
  "📂 06_SERIES_PHAP_HOI_NIEM_PHAT_CTNP",
  "   • Bài 01: Thấy Nghiệp Để Chuyển Hóa, Giữ Giới Để Tiến Tu - ĐĐ. Thích Tâm Hòa",
  "   • Bài 02: Pháp Hội Niệm Phật 03 - Hương Vị Giải Thoát",
  "",
  "📂 07_SERIES_KINH_DI_GIAO_PPUD",
  "   • Kế hoạch & Trích đoạn Timeline Kinh Di Giáo - ĐĐ. Thích Tâm Hòa",
  "",
  "📂 08_SERIES_LA_THU_KHAI_THI_SU_PHU (CHỈ DÀNH RIÊNG CHO SƯ PHỤ)",
  "   • Bài 01: Lá Thư Khai Thị Trước Thềm Năm Bính Ngọ - Thầy Viện Chủ Thích Tâm Hòa",
  "   • Bài 02: Lá Thư Mùa Trung Thu - Thầy Viện Chủ Thích Tâm Hòa",
  "   • Bài 03: Khai Tràng Thảm Lễ Nghi Thức Cúng Đàn (20 Phút) - Thầy Viện Chủ Thích Tâm Hòa",
  "",
  "📂 09_SERIES_KHOA_TU_TUOI_TRE_VA_PHUNG_SU",
  "   • Bài 01: Trái Tim Người Phụng Sự - ĐĐ. Thích Tâm Hòa",
  "   • Bài 02: Pháp Đàm Khóa Tu Tuổi Trẻ Buổi 1",
  "",
  "📂 10_SERIES_KHOA_LE_TRUYEN_THONG_VA_TUNG_KINH",
  "   • Bài 01: Pháp Thoại Huyết Bồn Trai Ngày 1",
  "   • Bài 02: Pháp Thoại Huyết Bồn Trai Ngày Khai Đàn",
  "   • Bài 03: Tụng Tỳ Ni Nhật Dụng Thiết Yếu - Bản Gốc",
  "   • Bài 04: Sám Nguyện - ĐĐ. Thích Thiện Mỹ",
  "",
  "--------------------------------------------------------------------------------",
  "B. PHÂN KHU TƯ LIỆU TỤNG ĐỌC CỦA CHƯ TĂNG (ĐÃ TÁCH BIỆT RIÊNG):",
  "",
  "📂 11_CHU_TANG_DIEN_NOM_CANH_SACH (ĐĐ. MINH HẠNH)",
  "   • 01. Cảnh Sách Diễn Nôm Sáng Chiều - ĐĐ. Minh Hạnh",
  "   • 02. Cảnh Sách Ngày Trai Buổi Chiều - ĐĐ. Minh Hạnh",
  "   • 03. Cảnh Sách Ngày Trai Buổi Sáng - ĐĐ. Minh Hạnh",
  "",
  "================================================================================"
];

fs.writeFileSync(path.join(postcastRoot, '00_DANH_MUC_VA_QUY_HOACH_POSTCAST.txt'), overviewLines.join('\r\n'), 'utf8');

// 2. CẬP NHẬT 00_BANG_TRA_CUU_PHAP_THOAI_POSTCAST.csv
const csvRows = [
  ["STT", "MÃ BÀI", "SERIES", "TÊN BÀI PHÁP THOẠI", "GIẢNG SƯ", "THỜI LƯỢNG", "ĐỊNH DẠNG", "TRẠNG THÁI", "ĐÃ LÊN WEB"],
  ["1", "#phapthoai 001", "Tôn Giả Mục Kiền Liên", "Hạnh Nguyện Ban Sơ", "ĐĐ. Thích Tâm Hòa", "75 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["2", "#phapthoai 002", "Tôn Giả Mục Kiền Liên", "Ưu Tư Thời Niên Thiếu", "ĐĐ. Thích Tâm Hòa", "82 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["3", "#phapthoai 003", "Tôn Giả Mục Kiền Liên", "Khơi Nguồn Hạnh Nguyện", "ĐĐ. Thích Tâm Hòa", "56 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["4", "#phapthoai 004", "Tôn Giả Mục Kiền Liên", "Giữ Vững Chí Nguyện", "ĐĐ. Thích Tâm Hòa", "65 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["5", "#phapthoai 005", "Tôn Giả Mục Kiền Liên", "Tự Do Đích Thực", "ĐĐ. Thích Tâm Hòa", "70 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["6", "#phapthoai 006", "Tôn Giả Mục Kiền Liên", "Mục Đích Tối Hậu", "ĐĐ. Thích Tâm Hòa", "85 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["7", "#phapthoai 007", "Tôn Giả Mục Kiền Liên", "Giữ Chất Người Tu", "ĐĐ. Thích Tâm Hòa", "62 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["8", "#phapthoai 008", "Tôn Giả Mục Kiền Liên", "Cánh Cửa Bất Tử", "ĐĐ. Thích Tâm Hòa", "78 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["9", "#phapthoai 009", "Tôn Giả Mục Kiền Liên", "Đạo Lộ Giải Thoát", "ĐĐ. Thích Tâm Hòa", "66 phút", "MP3 / WAV", "Hoàn tất master", "Có"],
  ["10", "#phapthoai 010", "Kinh Tạp A Hàm", "Lời Phật Dạy Về Hiếu Dưỡng Cha Mẹ - Phần 1", "ĐĐ. Thích Tâm Hòa", "68 phút", "MP3 / MP4", "Hoàn tất podcast", "Có"],
  ["11", "#phapthoai 011", "Kinh Tạp A Hàm", "Hiếu Dưỡng Cha Mẹ - Phần 2 - Hạnh Phúc Gia Đình", "ĐĐ. Thích Tâm Hòa", "62 phút", "MP3 / MP4", "Hoàn tất podcast", "Có"],
  ["12", "#phapthoai 012", "Kinh Tạp A Hàm", "Hiếu Dưỡng Cha Mẹ - Phần 3 - Báo Đáp Thâm Ân", "ĐĐ. Thích Tâm Hòa", "70 phút", "MP3 / MP4", "Hoàn tất podcast", "Có"],
  ["13", "#phapthoai 013", "Pháp Âm Chuyển Hóa", "Làm Thế Nào Để Gia Đình Hạnh Phúc", "Sa-môn Vô Trí", "58 phút", "MP3", "Hoàn tất master", "Có"],
  ["14", "#phapthoai 014", "Pháp Âm Chuyển Hóa", "Làm Cách Nào Để Duy Trì Sự Bình An", "Sa-môn Vô Trí", "54 phút", "MP3", "Hoàn tất master", "Có"],
  ["15", "#phapthoai 015", "Pháp Âm Chuyển Hóa", "Đâu Là Con Đường Đi Đến Hạnh Phúc", "Sa-môn Vô Trí", "60 phút", "MP3", "Hoàn tất master", "Có"],
  ["16", "#phapthoai 016", "Pháp Âm Chuyển Hóa", "Làm Việc Hiệu Quả Trong Chánh Niệm", "Sa-môn Vô Trí", "52 phút", "MP3", "Hoàn tất master", "Có"],
  ["17", "#phapthoai 017", "Bồ Đề Tâm Nghi Quỹ", "Điều Gì Giúp Người Con Phật Luôn Vững Vàng", "ĐĐ. Thích Tâm Hòa", "45 phút", "MP3 / DOCX", "Hoàn tất master", "Có"],
  ["18", "#phapthoai 018", "Lá Thư Sư Phụ", "Lá Thư Trước Thềm Năm Bính Ngọ", "ĐĐ. Thích Tâm Hòa", "25 phút", "MP3 / MP4", "Hoàn tất master", "Có"],
  ["19", "#phapthoai 019", "Một Ngày An Lạc", "Một Góc Nhìn Về Thực Dưỡng Oshawa", "ĐĐ. Thích Tâm Hòa", "60 phút", "MP3", "Đã bổ sung", "Có"],
  ["20", "#phapthoai 020", "Khóa Tu Tuổi Trẻ", "Trái Tim Người Phụng Sự", "ĐĐ. Thích Tâm Hòa", "50 phút", "MP3 / DOCX", "Hoàn tất master", "Có"],
  ["21", "#phapthoai 021", "Pháp Hội Niệm Phật", "Thấy Nghiệp Để Chuyển Hóa, Giữ Giới Để Tiến Tu", "ĐĐ. Thích Tâm Hòa", "75 phút", "MP3 / DOCX", "Hoàn tất master", "Có"],
  ["22", "#phapthoai 022", "Lá Thư Sư Phụ", "Lá Thư Mùa Trung Thu", "ĐĐ. Thích Tâm Hòa", "15 phút", "MP3", "Đã bổ sung", "Sẵn sàng"],
  ["23", "#phapthoai 023", "Nghi Lễ - Cúng Đàn", "Khai Tràng Thảm Lễ Nghi Thức Cúng Đàn (20 Phút)", "ĐĐ. Thích Tâm Hòa", "20 phút", "MP3", "Đã bổ sung", "Sẵn sàng"],
  ["24", "Tư liệu Chư Tăng", "Cảnh Sách Diễn Nôm Sáng Chiều", "ĐĐ. Minh Hạnh", "18 phút", "MP3", "Đã tách riêng", "Khu vực Chư Tăng"]
];

const csvContent = '\uFEFF' + csvRows.map(row => row.map(cell => `"${cell.replace(/"/g, '""')}"`).join(',')).join('\r\n');
fs.writeFileSync(path.join(postcastRoot, '00_BANG_TRA_CUU_PHAP_THOAI_POSTCAST.csv'), csvContent, 'utf8');

// 3. CẬP NHẬT HƯỚNG DẪN COPY CHO PHẬT TỬ TẠI E:\PHAP_THOAI_PHAT_TU_CHON_LOC
const phatTuGuide = [
  "================================================================================",
  "🛕 TÙNG LÂM HÒA PHÚC — BỘ PHÁP THOẠI TUYỂN CHỌN CHO QUÝ PHẬT TỬ 🛕",
  "================================================================================",
  "(Tài liệu nội bộ phục vụ việc sao chép thẻ nhớ/USB & chia sẻ Phật pháp)",
  "",
  "Kính bạch Quý Thầy, kính thưa Quý Phật tử và Ban Hoằng Pháp,",
  "",
  "Thư mục này chỉ tập trung các bài Pháp thoại và Khai thị của Thầy Viện Chủ Thích Tâm Hòa",
  "và Sa-môn Vô Trí, đã qua khâu lọc sạch tạp âm, chuẩn hóa âm lượng (Master Audio 44.1kHz),",
  "được phân loại mạch lạc theo từng Series và đánh số thứ tự rõ ràng.",
  "",
  "--------------------------------------------------------------------------------",
  "DANH MỤC CÁC BỘ PHÁP THOẠI CỦA SƯ PHỤ:",
  "--------------------------------------------------------------------------------",
  "",
  "📂 01. SERIES - TÔN GIẢ ĐẠI MỤC KIỀN LIÊN (09 TẬP)",
  "Giảng sư: Đại đức Thích Tâm Hòa",
  "• Tập 01: Hạnh Nguyện Ban Sơ (75 phút)",
  "• Tập 02: Ưu Tư Thời Niên Thiếu (82 phút)",
  "• Tập 03: Khơi Nguồn Hạnh Nguyện (56 phút)",
  "• Tập 04: Giữ Vững Chí Nguyện (65 phút)",
  "• Tập 05: Tự Do Đích Thực (70 phút)",
  "• Tập 06: Mục Đích Tối Hậu (85 phút)",
  "• Tập 07: Giữ Chất Người Tu (62 phút)",
  "• Tập 08: Cánh Cửa Bất Tử (78 phút)",
  "• Tập 09: Đạo Lộ Giải Thoát (66 phút)",
  "",
  "📂 02. SERIES - KINH TẠP A HÀM - HIẾU DƯỠNG CHA MẸ (03 TẬP)",
  "Giảng sư: Đại đức Thích Tâm Hòa",
  "• Tập 01: Lời Phật Dạy Về Hiếu Dưỡng Cha Mẹ (68 phút)",
  "• Tập 02: Hạnh Phúc Gia Đình (62 phút)",
  "• Tập 03: Báo Đáp Thâm Ân (70 phút)",
  "",
  "📂 03. SERIES - PHÁP ÂM CHUYỂN HÓA & BÌNH AN NỘI TÂM (SA-MÔN VÔ TRÍ)",
  "Giảng sư: Sa-môn Vô Trí",
  "• Bài 01: Làm Thế Nào Để Gia Đình Hạnh Phúc (58 phút)",
  "• Bài 02: Làm Cách Nào Để Duy Trì Sự Bình An (54 phút)",
  "• Bài 03: Đâu Là Con Đường Đi Đến Hạnh Phúc (60 phút)",
  "• Bài 04: Làm Việc Hiệu Quả Trong Chánh Niệm (52 phút)",
  "",
  "📂 04. SERIES - BỒ ĐỀ TÂM HÀNH TRÌ NGHI QUỸ",
  "Giảng sư: Đại đức Thích Tâm Hòa",
  "• Bài 01: Điều Gì Giúp Người Con Phật Luôn Vững Vàng (45 phút)",
  "• Bài 02: Trái Tim Người Phụng Sự (50 phút)",
  "",
  "📂 05. SERIES - LÁ THƯ KHAI THỊ SƯ PHỤ (ĐĐ. THÍCH TÂM HÒA)",
  "Giảng sư: Đại đức Thích Tâm Hòa",
  "• Bài 01: Lá Thư Khai Thị Trước Thềm Năm Bính Ngọ (25 phút)",
  "• Bài 02: Lá Thư Mùa Trung Thu (15 phút)",
  "• Bài 03: Một Góc Nhìn Về Thực Dưỡng Oshawa Dưới Ánh Sáng Phật Pháp (60 phút)",
  "",
  "--------------------------------------------------------------------------------",
  "MỤC RIÊNG: 📂 06. CHƯ TĂNG TỤNG ĐỌC DIỄN NÔM (ĐĐ. MINH HẠNH)",
  "• 01. Cảnh Sách Diễn Nôm Sáng Chiều (18 phút)",
  "• 02. Cảnh Sách Ngày Trai Buổi Chiều (15 phút)",
  "• 03. Cảnh Sách Ngày Trai Buổi Sáng (15 phút)",
  "================================================================================"
];

fs.writeFileSync(path.join(phatTuRoot, '00_HUONG_DAN_GUI_PHAP_THOAI_CHO_PHAT_TU.txt'), phatTuGuide.join('\r\n'), 'utf8');

console.log('✅ Đã cập nhật xong toàn bộ tài liệu chỉ mục và hướng dẫn!');
